<?php

namespace Database\Seeders;

use App\Models\Brand;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class BrandSeeder extends Seeder
{
    public function run(): void
    {
        $brands = [
            [
                'name' => 'Chanel',
                'slug' => 'chanel',
                'founded' => '1910',
                'founder' => 'Gabrielle "Coco" Chanel',
                'origin' => 'Paris, France',
                'category' => 'ラグジュアリー',
                'description' => '時代を超えたエレガンスと革新の象徴。ココ・シャネルが1910年にパリのrue Cambonに帽子店として創業。1921年に発表されたChanel No.5は、世界で初めてファッションデザイナーが作成した香水として歴史に名的地位を築きました。',
                'logo' => '/logo/chanel-logo.svg',
            ],
            [
                'name' => 'Dior',
                'slug' => 'dior',
                'founded' => '1946',
                'founder' => 'Christian Dior',
                'origin' => 'Paris, France',
                'category' => 'ラグジュアリー',
                'description' => 'フランス屈指のオートクチュールハウス。1947年の「New Look」発表は、戦後のファッション界に革命をもたらしました。同年に発表されたMiss Diorは、香水歴史においても重要なマイルストーンとなりました。',
                'logo' => '/logo/dior-logo.svg',
            ],
            [
                'name' => 'Gucci',
                'slug' => 'gucci',
                'founded' => '1921',
                'founder' => 'Guccio Gucci',
                'origin' => 'Florence, Italy',
                'category' => 'モダン',
                'description' => 'イタリア・フィレンツェ発の世界的ラグジュアリーブランド。馬具製造業から始まり、独特なクラフツマンシップと最高級の素材で知られています。1975年のGucci No.1が香水の第一章の始まりでした。',
                'logo' => '/logo/gucci-logo.svg',
            ],
            [
                'name' => 'Versace',
                'slug' => 'versace',
                'founded' => '1978',
                'founder' => 'Gianni Versace',
                'origin' => 'Milan, Italy',
                'category' => 'センシュアル',
                'description' => 'ミラノで誕生んだ大胆でグラマラスなブランド。 Gianni Versaceによる鮮やかなカラーと挑発的なスタイルは、ファッションの常識に挑戦し続けました。メドゥーサヘッドロゴはブランドのアイコニックな象徴です。',
                'logo' => '/logo/versace-logo.svg',
            ],
            [
                'name' => 'Chloe',
                'slug' => 'chloe',
                'founded' => '1952',
                'founder' => 'Gaby Aghion',
                'origin' => 'Paris, France',
                'category' => 'エレガント',
                'description' => 'パリジェンヌのエレガンスと自由な精神を表現したブランド。女性的でロマンティックなデザインは、時代を超えて愛されています。1975年のオリジナル香水はブランドの世界観を体現しています。',
                'logo' => '/logo/chloe-logo.svg',
            ],
            [
                'name' => 'SHIRO',
                'slug' => 'shiro',
                'founded' => '2002',
                'founder' => '-',
                'origin' => 'Japan',
                'category' => 'ナチュラル',
                'description' => '日本のミニマルな美学を追求したブランド。「白」をコンセプトに、シンプルで上質な製品をを展開。香りは日常に寄り添う控えめでありながらの存在感を大切にしています。',
                'logo' => '/logo/shiro-logo.svg',
            ],
            [
                'name' => 'COSME DECORTE',
                'slug' => 'cosme-decorte',
                'founded' => '1970',
                'founder' => '小林孝雄',
                'origin' => 'Japan',
                'category' => 'ラグジュアリー',
                'description' => '日本最高峰のプレステージスキンケアブランド。医学とスキンケアの融合を追求し、美の追究を続けています。',
                'logo' => null,
            ],
            [
                'name' => 'Issey Miyake',
                'slug' => 'issey-miyake',
                'founded' => '1992',
                'founder' => '三宅一生',
                'origin' => 'Japan',
                'category' => 'モダン',
                'description' => '三宅一生が創造する唯一無二人のフレグランス。「水」をコンセプトに、澄んだ透明感と気品を宿す不朽の名香を生み出し続けています。',
                'logo' => null,
            ],
            [
                'name' => '資生堂',
                'slug' => 'shiseido',
                'founded' => '1872',
                'founder' => '福原有信',
                'origin' => 'Japan',
                'category' => 'ラグジュアリー',
                'description' => '日本最古のビューティーカンパニー。140年以上にわたり、美の研究と创新を続けてきました。',
                'logo' => null,
            ],
            [
                'name' => 'ハナエモリ',
                'slug' => 'hanae-mori',
                'founded' => '1996',
                'founder' => '森英恵',
                'origin' => 'Japan',
                'category' => 'ラグジュアリー',
                'description' => '日本人女性として初めてパリ・オートクチュール組合に参加したデザイナー、森英恵のブランド。蝶をモチーフにした商品が象徴。',
                'logo' => null,
            ],
            [
                'name' => 'ケンゾー',
                'slug' => 'kenzo',
                'founded' => '1970',
                'founder' => '高田賢三',
                'origin' => 'France',
                'category' => 'モダン',
                'description' => 'パリの地でスタートしたストリートスポーツアイテムを基調としたブランド。自然とアートの融合大切にしています。',
                'logo' => null,
            ],
            [
                'name' => 'アナスイ',
                'slug' => 'anna-sui',
                'founded' => '1991',
                'founder' => 'アナ・スイ',
                'origin' => 'USA',
                'category' => 'ロマンティック',
                'description' => 'アメリカのデザイナーwith日本roots. 文化の融合と子供時代へのノスタルジーを表現。',
                'logo' => null,
            ],
            [
                'name' => 'ポール＆ジョー',
                'slug' => 'paul-joe',
                'founded' => '2002',
                'founder' => '・ソフィー・トローブ',
                'origin' => 'France/Japan',
                'category' => 'エレガント',
                'description' => 'フランスのデザイナー・ソフィー・トローブによるブランド。猫や花束など、ロマンチックで女性らしいモチーフが特徴。',
                'logo' => null,
            ],
            [
                'name' => 'ジルスチュアート',
                'slug' => 'jill-stuart',
                'founded' => '2005',
                'founder' => 'ジル・ステュアート',
                'origin' => 'USA',
                'category' => 'フェミニン',
                'description' => 'アメリカのジュエリーデザイナー、ジル・ステュアートによるブランド。キラキラと輝き、女性らしさを感じられるデザインが特徴。',
                'logo' => null,
            ],
            [
                'name' => 'トム・フォード',
                'slug' => 'tom-ford',
                'founded' => '2005',
                'founder' => 'トム・フォード',
                'origin' => 'USA',
                'category' => 'ラグジュアリー',
                'description' => '元グッチクリエイティブディレクターのトム・フォードが設立したラグジュアリーブランド。上質なマテリアルと官能的なデザインが特徴。',
                'logo' => null,
            ],
            [
                'name' => 'イヴ・サンローラン',
                'slug' => 'ysl',
                'founded' => '1961',
                'founder' => 'イヴ・サンローラン',
                'origin' => 'France',
                'category' => 'ラグジュアリー',
                'description' => ' Yves Saint Laurentが创立したフランスを代表するラグジュバリーブランド。 Freeな精神と美しいデザインが愛される。',
                'logo' => null,
            ],
            [
                'name' => 'プラダ',
                'slug' => 'prada',
                'founded' => '1913',
                'founder' => 'マリオ・プラダ',
                'origin' => 'Italy',
                'category' => 'ラグジュアリー',
                'description' => 'イタリア・ミラノ発の百年ブランド。ミニマリズムと機能美を追求し続けています。',
                'logo' => null,
            ],
            [
                'name' => 'ジョルジオ・アルマーニ',
                'slug' => 'armani',
                'founded' => '1975',
                'founder' => 'ジョルジオ・アルマーニ',
                'origin' => 'Italy',
                'category' => 'ラグジュアリー',
                'description' => 'イタリアンの极致。都会的で洗練されたデザインが特徴的なラグジュアリーブランド。',
                'logo' => null,
            ],
            [
                'name' => 'ジョーマローン',
                'slug' => 'jo-malone',
                'founded' => '1990',
                'founder' => 'ジョアン・マローン',
                'origin' => 'UK',
                'category' => 'プレミアム',
                'description' => 'ロンドン発のフレグランスブランド。シンプルなコラーと自由に Layeringできる点が特徴。',
                'logo' => null,
            ],
        ];

        foreach ($brands as $brand) {
            Brand::updateOrCreate(
                ['name' => $brand['name']],
                [
                    'slug' => $brand['slug'].'-'.Str::lower(Str::random(4)),
                    'founded' => $brand['founded'],
                    'founder' => $brand['founder'],
                    'origin' => $brand['origin'],
                    'category' => $brand['category'],
                    'description' => $brand['description'],
                    'logo' => $brand['logo'],
                ]
            );
        }
    }
}
