<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Category;
use App\Models\Product;
use App\Models\ProductVariant;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        // Skip check to allow re-seeding
        // if (Product::count() > 0) {
        //     return;
        // }

        $brands = Brand::all()->keyBy('name');
        $categories = Category::all()->keyBy('name');

        $products = $this->getAllProductsData();

        foreach ($products as $productData) {
            $brand = $brands[$productData['brand_name']] ?? null;
            $category = $categories[$productData['category_name']] ?? null;

            if (! $brand || ! $category) {
                continue;
            }

            $product = Product::create([
                'name' => $productData['name'],
                'slug' => Str::slug($productData['name']).'-'.Str::lower(Str::random(6)),
                'brand_id' => $brand->id,
                'category_id' => $category->id,
                'short_desc' => $productData['short_desc'],
                'long_desc' => $productData['long_desc'] ?? $productData['short_desc'],
                'is_active' => true,
                'featured' => $productData['featured'] ?? false,
                'attributes_json' => [
                    'notes' => $productData['notes'],
                    'gender' => $productData['gender'],
                ],
                'meta_json' => ['seo_title' => $productData['name']],
                'published_at' => now(),
            ]);

            $product->categories()->syncWithoutDetaching([$category->id]);

            foreach ($productData['variants'] as $variantData) {
                ProductVariant::create([
                    'product_id' => $product->id,
                    'sku' => $variantData['sku'],
                    'price_yen' => $variantData['price_yen'],
                    'sale_price_yen' => $variantData['sale_price_yen'] ?? null,
                    'option_json' => [
                        'size_ml' => $variantData['size_ml'],
                        'gender' => $productData['gender'],
                        'concentration' => $variantData['concentration'],
                    ],
                    'is_active' => true,
                ]);
            }
        }
    }

    private function getAllProductsData(): array
    {
        return array_merge(
            $this->getShiroProducts(),
            $this->getCosmeDecorteProducts(),
            $this->getIsseyMiyakeProducts(),
            $this->getShiseidoProducts(),
            $this->getHanaeMoriProducts(),
            $this->getKenzoProducts(),
            $this->getAnnaSuiProducts(),
            $this->getPaulJoeProducts(),
            $this->getJillStuartProducts(),
            $this->getExcelProducts(),
            $this->getChanelProducts(),
            $this->getDiorProducts(),
            $this->getTomFordProducts(),
            $this->getGucciProducts(),
            $this->getVersaceProducts(),
            $this->getChloeProducts(),
            $this->getYslProducts(),
            $this->getPradaProducts(),
            $this->getArmaniProducts(),
            $this->getJoMaloneProducts()
        );
    }

    // === SHIRO (6 products) ===
    private function getShiroProducts(): array
    {
        return [
            ['brand_name' => 'SHIRO', 'category_name' => 'フローラル EDP', 'name' => 'ホワイトリリー オードパルファン', 'gender' => 'women', 'short_desc' => '優雅で上品なフローラルの香り。ベルガモットやグリーンのフレッシュなトップノートから始まり、白いユリの花束が広がります。', 'long_desc' => '上品なフローラルに包まれる 洗練された「ホワイトリリー」の香り。リリーやマグノリアなどの花々の香りが広がる、華やかで清楚な香りが特長です。季節や性別を問わず使いやすく、つける場所によって香りの変化も楽しめます。', 'notes' => ['top' => 'ベルガモット、グリーン', 'middle' => 'ホワイトリリー、ジャスミン', 'base' => 'ムスク、シダーウッド'], 'featured' => true, 'variants' => [['sku' => 'SHIRO-WL-040', 'size_ml' => 40, 'price_yen' => 4180, 'concentration' => 'EDP'], ['sku' => 'SHIRO-WL-010', 'size_ml' => 10, 'price_yen' => 1430, 'concentration' => 'EDP']]],
            ['brand_name' => 'SHIRO', 'category_name' => 'フレッシュ EDT', 'name' => 'サボン オードパルファン', 'gender' => 'unisex', 'short_desc' => 'シンプルで爽やかな石鹸系の香り。レモンやオレンジの爽やかさにローズやジャスミンのフローラル感が加わり、清潔感のある香り。', 'long_desc' => '爽やかなフルーツが香る 清潔感漂う石けんをイメージした「サボン」の香り。レモン・オレンジ・ブラックカラントなどのフルーティーな香りに、やさしい甘さと石けんの清潔感を組み合わせた「サボン」は、SHIRO FRAGRANCE で最も人気の高い香りです。季節や性別を問わず使いやすく、つける場所によって香りの変化も楽しめます。', 'notes' => ['top' => 'レモン、オレンジ', 'middle' => 'ローズ、ジャスミン', 'base' => 'ムスク、アンバー'], 'featured' => true, 'variants' => [['sku' => 'SHIRO-SV-040', 'size_ml' => 40, 'price_yen' => 4180, 'concentration' => 'EDP'], ['sku' => 'SHIRO-SV-010', 'size_ml' => 10, 'price_yen' => 1430, 'concentration' => 'EDP']]],
            ['brand_name' => 'SHIRO', 'category_name' => 'フローラル EDP', 'name' => 'ホワイトティー オードパルファン', 'gender' => 'women', 'short_desc' => 'ホワイトティーの優雅な香り。白茶とベルガモットの調和が、洗練された印象を与えます。', 'long_desc' => '爽やかなシトラス調の中に深みあるティーが香る 落ち着きある「ホワイトティー」の香り。グレープフルーツやグリーンティーがフレッシュに広がる、上品な爽やかさの中にも落ち着きのある香りが特長です。季節や性別を問わず使いやすく、つける場所によって香りの変化も楽しめます。', 'notes' => ['top' => 'ベルガモット、レモン', 'middle' => 'ホワイトティー、ジャスミン', 'base' => 'ムスク、シダー'], 'variants' => [['sku' => 'SHIRO-WT-040', 'size_ml' => 40, 'price_yen' => 4180, 'concentration' => 'EDP']]],
            ['brand_name' => 'SHIRO', 'category_name' => 'シトラス EDT', 'name' => 'アールグレイ オードパルファン', 'gender' => 'unisex', 'short_desc' => '紅茶の香りとベルガモットの調和。落ち着きのある大人の香り。', 'long_desc' => 'ベルガモットが香る、フルーティーで華やかなアールグレイ。まるでティータイムのような、くつろぎの時間を演出する上品な香り。紅茶をひとくち含んだときに、ふんわりと広がる豊かな香りをイメージした「アールグレイ」。甘く華やかなトップノートから、上品で落ち着いたミドルノートへと次第に変化する、男女問わずお楽しみいただける香りです。フレッシュに広がり、時間とともに移ろう香りを、こころゆくまで楽しめます。', 'notes' => ['top' => 'ベルガモット、レモン', 'middle' => 'アールグレイティー、フローラル', 'base' => 'ムスク、ウッディ'], 'variants' => [['sku' => 'SHIRO-EG-040', 'size_ml' => 40, 'price_yen' => 4180, 'concentration' => 'EDP']]],
            ['brand_name' => 'SHIRO', 'category_name' => 'フローラル EDP', 'name' => 'キンモクセイ オードパルファン', 'gender' => 'women', 'short_desc' => '秋の訪れを感じさせる金木犀の香り。甘く優しい香りが特徴。', 'long_desc' => '甘くやさしい香りが広がる まるで、道端で香る金木犀そのものの香り。古くから三大香木として名高いキンモクセイは、可憐なオレンジ色の花をつけ、甘く優しい香りを広げます。果実を思わせるフルーティーさと上品な甘さの中に、ほんのり洋酒のようなアクセントを感じる香りです。時間とともに移ろい、華やかに広がるフレッシュな香りをお楽しみください。', 'notes' => ['top' => 'シトラス、グリーン', 'middle' => 'キンモクセイ、アプリコット', 'base' => 'ムスク、アンバー'], 'variants' => [['sku' => 'SHIRO-KM-040', 'size_ml' => 40, 'price_yen' => 4180, 'concentration' => 'EDP']]],
            ['brand_name' => 'SHIRO', 'category_name' => 'ボディミスト', 'name' => 'アイスミント ボディミスト', 'gender' => 'unisex', 'short_desc' => '暑い季節の救世主。メントールの清涼感が体を冷やします。', 'long_desc' => '持ち運びに便利なサイズのボディミスト。アウトドアシーンでも活躍する爽快な救世主。フレッシュな柑橘の香りとともに、メントールの冷感を味わえるボディミスト。さっぱりとした使用感ながら、保湿成分のゆずを配合しているため、エアコンや紫外線、発汗による乾燥対策も叶います。汗をかいたときにも感じる冷たさで、爽快な肌が長続き。携帯に便利なミニサイズで屋外のクールダウンにも活躍します。', 'notes' => ['top' => 'ミント、レモン', 'middle' => 'ハーブ、フローラル', 'base' => 'ムスク'], 'variants' => [['sku' => 'SHIRO-IM-100', 'size_ml' => 100, 'price_yen' => 2750, 'concentration' => 'Mist']]],
        ];
    }

    // === COSME DECORTE (6 products) ===
    private function getCosmeDecorteProducts(): array
    {
        return [
            ['brand_name' => 'COSME DECORTE', 'category_name' => 'シトラス EDT', 'name' => 'キモノ ユイ オードトワレ', 'gender' => 'women', 'short_desc' => '和情緒あふれるシトラスフローラル。爽やかでほろ苦い日本のカンキツと軽快なピンクペッパーが弾けるトップノート。', 'long_desc' => '爽やかでほろ苦い酢橘と軽やかなピンクペッパーではじけるようなトップノートを演出。オレンジフラワーを中心としたブーケのようなミドルノートは透きとおる初夏の日差しのように香ります。最後にやわらかなバニラが際立つ魅惑的なウッディノートによって、やさしい幸福を包み込みます。', 'notes' => ['top' => '日本のカンキツ、ピンクペッパー', 'middle' => 'オレンジフラワー', 'base' => 'バニラ'], 'featured' => true, 'variants' => [['sku' => 'CD-KIM-YUI-50', 'size_ml' => 50, 'price_yen' => 7700, 'concentration' => 'EDT'], ['sku' => 'CD-KIM-YUI-15', 'size_ml' => 15, 'price_yen' => 3520, 'concentration' => 'EDT']]],
            ['brand_name' => 'COSME DECORTE', 'category_name' => 'フローラル EDP', 'name' => 'キモノ ツヤ オードトワレ', 'gender' => 'women', 'short_desc' => 'りんごとピオニー、モクレンの優雅な香り。', 'long_desc' => '上品な木蓮を中心に、透明感のあるローズ、甘くやさしいピオニーが織りなす、センシュアルなブーケのように。ユズのアクセントで一層華やかなトップから香りが移ろい、ラストノートではムスクやシダーウッドが全体をまとめ上げ、落ち着きのある上質な香りへと昇華してゆきます。', 'notes' => ['top' => 'りんご、カシス', 'middle' => 'ピオニー、モクレン', 'base' => 'シダーウッド'], 'variants' => [['sku' => 'CD-KIM-TSU-50', 'size_ml' => 50, 'price_yen' => 7700, 'concentration' => 'EDT']]],
            ['brand_name' => 'COSME DECORTE', 'category_name' => 'ウッディ EDP', 'name' => 'キモノ キヒン オードトワレ', 'gender' => 'women', 'short_desc' => '梅、リリー、スミレの凛とした香り。', 'long_desc' => '内に秘めた強さと美しさを引き出すように。菖蒲の持つエレガントさを、落ち着きのあるベルガモットの香りから始まる、パウダリーなフローラルノートで表現しました。そこへ輝くようなジャスミンのアクセントが重なり、今までにない洗練された印象に。ラストはパチュリやサンダルウッドによって甘く高貴な、忘れがたい余韻を残します。', 'notes' => ['top' => 'プラム、梅', 'middle' => 'リリー、スミレ', 'base' => 'ムスク'], 'variants' => [['sku' => 'CD-KIM-KIH-50', 'size_ml' => 50, 'price_yen' => 7700, 'concentration' => 'EDT']]],
            ['brand_name' => 'COSME DECORTE', 'category_name' => 'フローラル EDP', 'name' => 'キモノ ウララ オードトワレ', 'gender' => 'women', 'short_desc' => '蓮、ローズ、スズランの透明感ある香り。', 'long_desc' => '艶めいて、どこまでも麗らか。神秘的な睡蓮とみずみずしい林檎によるいきいきとしたフレッシュフローラル。麗らかな花々と果実が放つ、あふれんばかりの生命力。フレッシュな林檎やメロンから始まるトップノート。そこへ神聖ささえ纏う清らかな睡蓮が香り、みずみずしく鮮やかな印象に。ラストはサンダルウッドを中心としたウッディノートが心地よく響きます。', 'notes' => ['top' => '蓮、フローラル', 'middle' => 'ローズ、スズラン', 'base' => 'ムスク'], 'variants' => [['sku' => 'CD-KIM-URA-50', 'size_ml' => 50, 'price_yen' => 7700, 'concentration' => 'EDT']]],
            ['brand_name' => 'COSME DECORTE', 'category_name' => 'フローラル EDP', 'name' => 'キモノ リン オードトワレ', 'gender' => 'women', 'short_desc' => 'アイリス、スミレ、シダーの上品な香り。', 'long_desc' => '凛として佇む存在感。甘美な梅をプロローグにした強く優美なウッディフローラル。強さと優美さの二面性。古くから日本で愛されてきた梅が、光を放つようなジャスミンの香りと重なり、官能的で大胆な表情を見せます。その力強さと対比するように、ラストノートはパチュリがやさしく香り、安らぎに深く包み込まれます。', 'notes' => ['top' => 'アイリス、フローラル', 'middle' => 'スミレ', 'base' => 'シダー、アンバー'], 'variants' => [['sku' => 'CD-KIM-RIN-50', 'size_ml' => 50, 'price_yen' => 7700, 'concentration' => 'EDT']]],
            ['brand_name' => 'COSME DECORTE', 'category_name' => 'フローラル EDP', 'name' => 'AQ オードパルファン', 'gender' => 'women', 'short_desc' => '金香木と純白の花々によるフレッシュフローラルムスキー。スキンケア効果もある香水。', 'long_desc' => '爽やかでいきいきとしたシトラスをトップに、みずみずしく神聖な金香木、パウダリーな甘さのある月下美人、やさしくラグジュアリーな白檀が気品と華やかさを奏でます。', 'notes' => ['top' => '金香木、シトラス', 'middle' => '白い花々', 'base' => 'ムスク'], 'variants' => [['sku' => 'CD-AQ-100', 'size_ml' => 100, 'price_yen' => 22000, 'concentration' => 'EDP']]],
        ];
    }

    // === ISSEY MIYAKE (6 products) ===
    private function getIsseyMiyakeProducts(): array
    {
        return [
            ['brand_name' => 'Issey Miyake', 'category_name' => 'フレッシュ EDT', 'name' => 'ロードゥ イッセイ オードトワレ', 'gender' => 'women', 'short_desc' => 'アクアティックフローラルの先駆け。澄んだ透明感と気品を宿す不朽の名香。', 'long_desc' => '「世界で最も美しく最もピュアなフレグランス。それは、純粋で透明感のある水の香り。」唯一無二のフレグランス。三宅一生が初めて手がけたフレグランスのコンセプトは、ピュアでフレッシュな水。1992 年、香りの世界にひとつの新しい流れを創り出したロードゥ イッセイはフレグランスを代表する香りです。フレッシュなホワイトフラワーブーケと爽やかなアクアティックフローラルの香り。', 'notes' => ['top' => 'シトラス、フローラル', 'middle' => 'アクアティックノート、ホワイトフラワー', 'base' => 'ムスク、シダー'], 'featured' => true, 'variants' => [['sku' => 'IM-LDI-EDT-50', 'size_ml' => 50, 'price_yen' => 9350, 'concentration' => 'EDT'], ['sku' => 'IM-LDI-EDT-100', 'size_ml' => 100, 'price_yen' => 14300, 'concentration' => 'EDT']]],
            ['brand_name' => 'Issey Miyake', 'category_name' => 'フローラル EDP', 'name' => 'ロードゥ イッセイ オードパルファム インテンス', 'gender' => 'women', 'short_desc' => '海の神秘と豊かさを表現。ポシドニアのグリーンアコードとイランイランの甘美さ。', 'long_desc' => '神秘に満ちた深い海からインスパイアされたオードパルファム インテンス。海底に広がる神秘的なポシドニアの草原が着想源。「ロードゥ イッセイ」を象徴するアクアティック フローラル ノートにポシドニアのグリーン アコードが深みを加え、輝きを放つイランイランと官能的なバニラが香りを引き立てます。', 'notes' => ['top' => 'ポシドニア、グリーンアコード', 'middle' => 'イランイラン、フローラル', 'base' => 'バニラ、ウッディ'], 'variants' => [['sku' => 'IM-LDI-EDPI-30', 'size_ml' => 30, 'price_yen' => 12320, 'concentration' => 'EDP'], ['sku' => 'IM-LDI-EDPI-50', 'size_ml' => 50, 'price_yen' => 17270, 'concentration' => 'EDP'], ['sku' => 'IM-LDI-EDPI-100', 'size_ml' => 100, 'price_yen' => 24200, 'concentration' => 'EDP']]],
            ['brand_name' => 'Issey Miyake', 'category_name' => 'フレッシュ EDT', 'name' => 'ロードゥ イッセイ プールオム オードトワレ', 'gender' => 'men', 'short_desc' => 'みずみずしい柑橘とウッディの調和。男性らしい清涼感。', 'long_desc' => '「山合いにほとばしる急流のように力強く爽やかなセンセーション」。大自然から湧きいずる水の清浄な力強さからインスピレーションを得てクリエートしたフレグランス。流行に左右されない、本物の個性を持つ香り。自然なエレガンスと爽やかさのハーモニーがあふれ出る香りです。', 'notes' => ['top' => 'ユズ、シトラス', 'middle' => 'スパイス、ウォータリーノート', 'base' => 'サンダルウッド、ムスク'], 'variants' => [['sku' => 'IM-LDIPH-EDT-40', 'size_ml' => 40, 'price_yen' => 8250, 'concentration' => 'EDT'], ['sku' => 'IM-LDIPH-EDT-75', 'size_ml' => 75, 'price_yen' => 12430, 'concentration' => 'EDT'], ['sku' => 'IM-LDIPH-EDT-125', 'size_ml' => 125, 'price_yen' => 17270, 'concentration' => 'EDT']]],
            ['brand_name' => 'Issey Miyake', 'category_name' => 'ウッディ EDP', 'name' => 'ロードゥ イッセイ プールオム オードパルファム', 'gender' => 'men', 'short_desc' => '海からインスパイアされた豊かな香り。深みのあるウッディアロマ。', 'long_desc' => '神秘に満ちた深い海を表現した、豊かで鮮烈な香り。', 'notes' => ['top' => 'シトラス、スパイス', 'middle' => 'ウッディノート、ラベンダー', 'base' => 'パチュリ、サンダルウッド'], 'variants' => [['sku' => 'IM-LDIPH-EDP-40', 'size_ml' => 40, 'price_yen' => 9570, 'concentration' => 'EDP'], ['sku' => 'IM-LDIPH-EDP-75', 'size_ml' => 75, 'price_yen' => 12430, 'concentration' => 'EDP']]],
            ['brand_name' => 'Issey Miyake', 'category_name' => 'フローラル EDP', 'name' => 'ロードゥ イッセイ ピュア オードトワレ', 'gender' => 'women', 'short_desc' => '純粋でフレッシュな水の香り。ムスキーアクアティックフローラル。', 'long_desc' => 'もぎたてのマンダリンの弾けるような香りが刺激的。真珠色の光をたっぷりと浴びた花びらが次つぎと開花するような、みずみずしいフローラルシトラスの香り。純粋でフレッシュな水の香りを現代的に解釈したフレグランスです。', 'notes' => ['top' => 'シトラス、マリン', 'middle' => 'フローラル、アクアティック', 'base' => 'ムスク、シダー'], 'variants' => [['sku' => 'IM-LDIP-EDT-50', 'size_ml' => 50, 'price_yen' => 8800, 'concentration' => 'EDT']]],
            ['brand_name' => 'Issey Miyake', 'category_name' => 'フローラル EDP', 'name' => 'ロードゥ イッセイ ソーラーバイオレット', 'gender' => 'women', 'short_desc' => '華やかなバイオレットの香り。太陽の光を浴びた花々のブーケ。', 'long_desc' => '春の太陽がぬくもりを添える、水と光のコントラスト。明るさに満ちたバイオレットが溶け込んだフレグランス。まばゆい春の太陽がぬくもりを添える、水と光のコントラストによる情熱に満ちた物語。澄み切ったバイオレットの繊細さが水と融合し、ハーモニーを奏でます。', 'notes' => ['top' => 'シトラス、グリーン', 'middle' => 'バイオレット、アイリス', 'base' => 'ムスク、ウッディ'], 'variants' => [['sku' => 'IM-LDI-SV-50', 'size_ml' => 50, 'price_yen' => 9900, 'concentration' => 'EDT']]],
        ];
    }

    // === SHISEIDO (6 products) ===
    private function getShiseidoProducts(): array
    {
        return [
            ['brand_name' => '資生堂', 'category_name' => 'オリエンタル EDP', 'name' => 'SHISEIDO ZEN オードパルファム', 'gender' => 'women', 'short_desc' => 'みずみずしく、強く、甘く。今を生きる女性たちへおくる、歓びを呼び覚ます香水。', 'long_desc' => 'みずみずしく、強く、甘く。女性である歓びを呼び覚ます。それは無限の歓喜。', 'notes' => ['top' => 'フルーツ、シトラス', 'middle' => 'フローラル、アンバー', 'base' => 'ウッド、パチュリ'], 'featured' => true, 'variants' => [['sku' => 'SHI-ZEN-30', 'size_ml' => 30, 'price_yen' => 5500, 'concentration' => 'EDP'], ['sku' => 'SHI-ZEN-50', 'size_ml' => 50, 'price_yen' => 8250, 'concentration' => 'EDP']]],
            ['brand_name' => '資生堂', 'category_name' => 'フローラル EDP', 'name' => 'SHISEIDO ギンザ オードパルファム', 'gender' => 'women', 'short_desc' => '女性の秘めた美しさを表現した香り。銀座のエッセンスを凝縮。', 'long_desc' => '繊細さと激しさ、知性と情熱。女性の美しい二面性を表現したオードパルファム。ジャスミンを中心とした軽やかな花々の香りと、ヒノキに研ぎ澄まされたモクレン、和蘭が神秘的な雰囲気を醸し出す、女性らしい活気に満ちた、エレガントでタイムレスな香りを表現。', 'notes' => ['top' => 'シトラス、フローラル', 'middle' => 'ジャスミン、ローズ', 'base' => 'ムスク、サンダルウッド'], 'variants' => [['sku' => 'SHI-GIN-30', 'size_ml' => 30, 'price_yen' => 9350, 'concentration' => 'EDP'], ['sku' => 'SHI-GIN-50', 'size_ml' => 50, 'price_yen' => 13750, 'concentration' => 'EDP'], ['sku' => 'SHI-GIN-90', 'size_ml' => 90, 'price_yen' => 18700, 'concentration' => 'EDP']]],
            ['brand_name' => '資生堂', 'category_name' => 'ウッディ EDP', 'name' => 'BAUM ウッドランドウィンズ オーデコロン', 'gender' => 'unisex', 'short_desc' => '湖畔の林に吹く風のような、清々しい香り。森林浴のような癒し。', 'long_desc' => '湖畔の林に吹く風のような、清々しい香り。心洗われるようなクリーンさと果樹の香りの調和。その調和が爽快感をもたらします。', 'notes' => ['top' => 'ベルガモット、カモミール', 'middle' => 'サイプレス、コリアンダー、ゼラニウム、ローズ', 'base' => 'シダーウッド、ベチバー'], 'variants' => [['sku' => 'SHI-BM-WW-60', 'size_ml' => 60, 'price_yen' => 14850, 'concentration' => 'EDC']]],
            ['brand_name' => '資生堂', 'category_name' => 'ウッディ EDP', 'name' => 'BAUM フォレストエンブレイス オーデコロン', 'gender' => 'unisex', 'short_desc' => '深い静寂の森で、瞑想する香り。スモーキーで神秘的なハーモニー。', 'long_desc' => '深い静寂の森で、瞑想する香り。樹木や植物のスモーキーで神秘的なハーモニー。深緑の中の安らぎ感をもたらします。', 'notes' => ['top' => 'カルダモン、ライム', 'middle' => 'イランイラン、ジャスミン、ローズマリー', 'base' => 'シダーウッド、パチュリ'], 'variants' => [['sku' => 'SHI-BM-FE-60', 'size_ml' => 60, 'price_yen' => 14850, 'concentration' => 'EDC']]],
            ['brand_name' => '資生堂', 'category_name' => 'フローラル EDP', 'name' => 'マジョリカマジョルカ マジョロマンティカ', 'gender' => 'women', 'short_desc' => 'とろ～り一滴で「女の子」の血が騒ぎ出す、甘い甘い魔法の媚薬。', 'long_desc' => 'とろ～り、魔法の媚薬フレグランス。いくつになっても永遠の「女の子」でいられそうな甘い甘い香りは、まるで魔法の媚薬。赤い果実や甘く可憐に香り立つブーケ、メープルシロップなどを凝縮したような、スイートでロマンティックな香りです。煮つめたようなとろーりとした一滴が、身につける人の心を騒がします。', 'notes' => ['top' => 'レッドフルーツ、ジューシー', 'middle' => 'フローラルスイート', 'base' => 'スイート、ミステリアス'], 'variants' => [['sku' => 'MJ-MM-20', 'size_ml' => 20, 'price_yen' => 1760, 'concentration' => 'EDT']]],
            ['brand_name' => '資生堂', 'category_name' => 'フレッシュ EDT', 'name' => 'SHISEIDO メン オードトワレ', 'gender' => 'men', 'short_desc' => '資生堂の男性用フレグランス。清潔感と落ち着きのある香り。', 'long_desc' => '日本原産の破竹で男の強さを、檜の抽出香料で男の知性を表現した、研ぎ澄まされた力強さの中にぬくもりを感じる、ウッディースパイシーグリーンの品格のある香りです。', 'notes' => ['top' => 'シトラス、グリーン', 'middle' => 'スパイス、フローラル', 'base' => 'ウッディ、ムスク'], 'variants' => [['sku' => 'SHI-MEN-50', 'size_ml' => 50, 'price_yen' => 6050, 'concentration' => 'EDT']]],
        ];
    }

    // === HANAE MORI (6 products) ===
    private function getHanaeMoriProducts(): array
    {
        return [
            ['brand_name' => 'ハナエモリ', 'category_name' => 'フローラル EDP', 'name' => 'バタフライ オードパルファム', 'gender' => 'women', 'short_desc' => '森英恵を象徴する蝶のモチーフ。甘く官能的なフローラルの香り。', 'long_desc' => '森英恵を象徴する蝶のモチーフ。甘く官能的なフローラルの香り。', 'notes' => ['top' => 'レッドフルーツ、ストロベリー', 'middle' => 'ピンクピオニー、アーモンドブロッサム', 'base' => 'アーモンドウッド、バニラ'], 'featured' => true, 'variants' => [['sku' => 'HM-BF-EDP-50', 'size_ml' => 50, 'price_yen' => 8800, 'concentration' => 'EDP'], ['sku' => 'HM-BF-EDP-100', 'size_ml' => 100, 'price_yen' => 12100, 'concentration' => 'EDP']]],
            ['brand_name' => 'ハナエモリ', 'category_name' => 'フローラル EDP', 'name' => 'バタフライ オードトワレ', 'gender' => 'women', 'short_desc' => '春の渦巻く蝶に敬意を表した、フルーティで官能的な香り。', 'long_desc' => 'バタフライのオードトワレバージョン。森英恵といえば蝶のモチーフ。ボトルキャップには羽をたたんだ蝶があしらわれています。象徴的で時代を超越した嗅覚の構成を通して、春の渦巻く蝶に敬意を表しています。自然に生命を吹き込む花と森の香りのエッセンスの世界。フルーティーで官能的、エレガントで洗練された香り。', 'notes' => ['top' => 'ブラックカラント、ストロベリー', 'middle' => 'ピオニー、ローズ', 'base' => 'アーモンド、バニラ'], 'variants' => [['sku' => 'HM-BF-EDT-50', 'size_ml' => 50, 'price_yen' => 6600, 'concentration' => 'EDT']]],
            ['brand_name' => 'ハナエモリ', 'category_name' => 'フローラル EDP', 'name' => 'パープルバタフライ オードパルファム', 'gender' => 'women', 'short_desc' => '神秘的でエレガントなパープルの世界。深みのあるフローラル。', 'long_desc' => 'パープルという名前のとおり、イリスやヴァイオレットがメインとなった、シンプルなパウダリック・フローラルで、化粧品のようなたたずまいを感じさせます。クラシックでもモダンでもない、タイムレスな香りで、女性であればだれにでも愛されそうな一品です。ライトな香りですので、シーズンを問わずにお使いいただけるでしょう。', 'notes' => ['top' => 'フルーツ、シトラス', 'middle' => 'フローラル、スミレ', 'base' => 'ムスク、ウッディ'], 'variants' => [['sku' => 'HM-PB-50', 'size_ml' => 50, 'price_yen' => 8800, 'concentration' => 'EDP']]],
            ['brand_name' => 'ハナエモリ', 'category_name' => 'ウッディ EDP', 'name' => 'HM オードパルファム', 'gender' => 'women', 'short_desc' => 'シンプルで洗練された香り。モダンなウッディフローラル。', 'long_desc' => "HM, the very first men's fragrance by Hanae Mori, stands as the iconic classic of the brand. It embodies elegance, a vision shared with her sons, Akira and Kei. Resolutely modern, this fragrance encapsulates the contemporary and confident man. Its refined scent unfolds with an invigorating burst of bergamot and lavender. Notes of jasmine and woods mingle at its heart, creating an unforgettable masculine trail.", 'notes' => ['top' => 'シトラス、フルーツ', 'middle' => 'フローラル、スパイス', 'base' => 'ウッディ、ムスク'], 'variants' => [['sku' => 'HM-HM-50', 'size_ml' => 50, 'price_yen' => 7700, 'concentration' => 'EDP']]],
            ['brand_name' => 'ハナエモリ', 'category_name' => 'フローラル EDP', 'name' => 'ハナエ オードパルファム', 'gender' => 'women', 'short_desc' => '東洋と西洋の融合を表現した香り。', 'long_desc' => '1968 年に初めてモリハナエから販売された香水をリニューアルしたもの。最初の香り立ちが、大人っぽい重めのオリエンタル。HANAE MORI の BUTTERFLY を愛する人のための香り。', 'notes' => ['top' => 'シトラス、グリーン', 'middle' => 'フローラル、フルーティ', 'base' => 'ムスク、サンダルウッド'], 'variants' => [['sku' => 'HM-HANA-50', 'size_ml' => 50, 'price_yen' => 7700, 'concentration' => 'EDP']]],
            ['brand_name' => 'ハナエモリ', 'category_name' => 'フレッシュ EDT', 'name' => 'HiM オードトワレ', 'gender' => 'men', 'short_desc' => '男性のためのフレッシュでモダンな香り。', 'long_desc' => '男性のためのフレッシュでモダンな香り。ベルガモット、マンダリンオレンジ、グレーペッパー、バイオレットリーフのトップから、ジャスミン、アイリス、スズラン、ローズのミドルへ。サンダルウッドとスパイスのウッディでスパイシーなベース。冒険心あふれる男性のためのフレグランス。', 'notes' => ['top' => 'シトラス、アロマティック', 'middle' => 'スパイス、ウッディ', 'base' => 'ムスク、シダー'], 'variants' => [['sku' => 'HM-HIM-50', 'size_ml' => 50, 'price_yen' => 6600, 'concentration' => 'EDT']]],
        ];
    }

    // === KENZO (6 products) ===
    private function getKenzoProducts(): array
    {
        return [
            ['brand_name' => 'ケンゾー', 'category_name' => 'フローラル EDP', 'name' => 'フラワー バイ ケンゾー オードパルファム', 'gender' => 'women', 'short_desc' => '一輪のポピーが咲き誇るような、シンプルで力強いフローラルの香り。', 'notes' => ['top' => 'マンダリン、ブラックカラント', 'middle' => 'ポピー、ローズ、ジャスミン', 'base' => 'バニラ、ムスク、インセンス'], 'featured' => true, 'variants' => [['sku' => 'KEN-FLW-EDP-30', 'size_ml' => 30, 'price_yen' => 6270, 'concentration' => 'EDP'], ['sku' => 'KEN-FLW-EDP-50', 'size_ml' => 50, 'price_yen' => 8250, 'concentration' => 'EDP']]],
            ['brand_name' => 'ケンゾー', 'category_name' => 'フローラル EDP', 'name' => 'フラワー バイ ケンゾー オードトワレ', 'gender' => 'women', 'short_desc' => '軽やかでフレッシュなポピーの香り。日常使いにぴったり。', 'long_desc' => '軽やかでフレッシュなポピーの香り。日常使いにぴったり。アスファルトの街に力強く咲く一輪の花。つけた瞬間ブルガリアンローズなどのフローラルフラワーの香りに包まれ、時間を重ねると共にホワイトムスクやバニラのやさしい香りへ。現代的な感覚にあふれた、官能的なフローラルの香り。', 'notes' => ['top' => 'マンダリン、カシス', 'middle' => 'ポピー、ジャスミン', 'base' => 'ムスク、バニラ'], 'variants' => [['sku' => 'KEN-FLW-EDT-30', 'size_ml' => 30, 'price_yen' => 5610, 'concentration' => 'EDT'], ['sku' => 'KEN-FLW-EDT-50', 'size_ml' => 50, 'price_yen' => 7150, 'concentration' => 'EDT']]],
            ['brand_name' => 'ケンゾー', 'category_name' => 'フレッシュ EDT', 'name' => 'ローパ ケンゾー プールオム オードトワレ', 'gender' => 'men', 'short_desc' => '水のエッセンスを凝縮したフレッシュな香り。', 'long_desc' => '柚子独特の心地よい苦味がトップノートを引きしめます。そしてミドルにグリーンノートのロータスリーフや、アクアミントが現れ、落ち着いた印象を与えます。すっきりとした爽やかさのあるアクアティックシトラスに、ウッドやホワイトムスクでスパイシーな甘さを与えた香り。', 'notes' => ['top' => 'ユズ、レモン', 'middle' => 'ミント、アクアティック', 'base' => 'サンダルウッド、ムスク'], 'variants' => [['sku' => 'KEN-LEAU-30', 'size_ml' => 30, 'price_yen' => 4840, 'concentration' => 'EDT'], ['sku' => 'KEN-LEAU-50', 'size_ml' => 50, 'price_yen' => 6270, 'concentration' => 'EDT'], ['sku' => 'KEN-LEAU-100', 'size_ml' => 100, 'price_yen' => 8800, 'concentration' => 'EDT']]],
            ['brand_name' => 'ケンゾー', 'category_name' => 'フレッシュ EDT', 'name' => 'アクア ケンゾー プールオム オードトワレ', 'gender' => 'men', 'short_desc' => '深い海のエネルギーを表現したアクアティックフレグランス。', 'long_desc' => '美しく透明感に溢れた水の世界の香り。新たな次元の清々しさが、鮮烈なセンセーションを与え、身にまとう者を自由にします。シリーズ共通のユズが媚薬にも似た鮮烈な印象をもたらす、フレッシュかつ力強い香り。ユズがライムやピンクペッパーと出合い、力強く香ります。', 'notes' => ['top' => 'シトラス、ユズ', 'middle' => 'アクアティックノート、ミント', 'base' => 'シダー、ムスク'], 'variants' => [['sku' => 'KEN-AQ-30', 'size_ml' => 30, 'price_yen' => 4950, 'concentration' => 'EDT'], ['sku' => 'KEN-AQ-50', 'size_ml' => 50, 'price_yen' => 6490, 'concentration' => 'EDT']]],
            ['brand_name' => 'ケンゾー', 'category_name' => 'フローラル EDP', 'name' => 'ケンゾー ワールド オードパルファム', 'gender' => 'women', 'short_desc' => '世界を舞台にした自由で楽しい香り。', 'long_desc' => 'ケンゾーより、待望の新作フレグランス「ケンゾー ワールド」登場。飛び交うハート、まばゆいまでを香りいっぺんの星の瞬きが絶え間なく輝かせ、自由を解き放つような、まばゆいまでに、生き生きとした香り。世界のすべての美しいもの、ミネルヴァのハートのような輝きで。', 'notes' => ['top' => 'ペア、フローラル', 'middle' => 'ピオニー、ジャスミン', 'base' => 'アンバー、ムスク'], 'variants' => [['sku' => 'KEN-WRLD-30', 'size_ml' => 30, 'price_yen' => 5830, 'concentration' => 'EDP'], ['sku' => 'KEN-WRLD-50', 'size_ml' => 50, 'price_yen' => 7700, 'concentration' => 'EDP']]],
            ['brand_name' => 'ケンゾー', 'category_name' => 'フローラル EDP', 'name' => 'フラワー エア オードパルファム', 'gender' => 'women', 'short_desc' => '軽やかに舞い上がるポピーの香り。エアリーでモダンな印象。', 'long_desc' => '空に解き放たれたポピーの花。ブランドを象徴する花、ポピーに抱いた、新たな夢。フラワー バイ ケンゾーが描いてきた、「都会に咲く一輪の花」という詩的な物語を超え、その世界は高く、遠くへと広がっていきます。アスファルトに根をおろし咲いていたその真っ赤なポピーが、宙に舞い上がっていったなら・・・。物語の新たな章、それは、KENZO を象徴するポピーのために創られた羽のように軽やかなきらめくフローラルな香り。', 'notes' => ['top' => 'グリーンアップル、カシス', 'middle' => 'ポピー、ローズ、フリージア', 'base' => 'ムスク、サンダルウッド'], 'variants' => [['sku' => 'KEN-FAIR-30', 'size_ml' => 30, 'price_yen' => 7920, 'concentration' => 'EDP']]],
        ];
    }

    // === ANNA SUI (6 products) ===
    private function getAnnaSuiProducts(): array
    {
        return [
            ['brand_name' => 'アナスイ', 'category_name' => 'フルーティー EDT', 'name' => 'シークレットウィッシュ オードトワレ', 'gender' => 'women', 'short_desc' => '「願うことが願いを叶える」をテーマにした、フルーティーフローラルムスキーの香り。', 'long_desc' => '童話のような喜びの香りに包まれる「シークレット ウィッシュ」。轻轻一噴で、豊かな果香が溢れ出します：爽やかなレモン、夏のメロン、ベルベットのようなマリーゴールド、そして柔らかくアプリコットのような花々。その後、パイナップルと控えめなブラックカラントが誘惑的な魅力を加えます。ベースはムスク、ホワイトシダーウッド、アンバーが組み合わさり、この香水を魅力的で官能的に仕上げます。2005 年に発売された不朽の名香で、フルーティフローラルの香調。', 'notes' => ['top' => 'レモン、メロン、タジェット', 'middle' => 'ブラックカラント、パイナップル', 'base' => 'ホワイトシダー、アンバー、スキンムスク'], 'featured' => true, 'variants' => [['sku' => 'AS-SW-30', 'size_ml' => 30, 'price_yen' => 5610, 'concentration' => 'EDT'], ['sku' => 'AS-SW-75', 'size_ml' => 75, 'price_yen' => 10120, 'concentration' => 'EDT']]],
            ['brand_name' => 'アナスイ', 'category_name' => 'フルーティー EDT', 'name' => 'ラッキーウィッシュ オードトワレ', 'gender' => 'women', 'short_desc' => '幸せを呼び込むフレッシュでフルーティな香り。', 'long_desc' => '幸せを呼び込むフレッシュでフルーティな「ラッキーウィッシュ」。純粋な喜び、愛、そして幸運が漂う、フローラル シトラス ウッディの香りです。フローズンレモン、ジューシーグレープフルーツのトップから、フローラルとフルーティのミドルへ。ムスクとウッディの温かみのあるベース。幸せを呼び込むフレッシュでフルーティな香りで、ロマンティックでナチュラルな気分にさせます。', 'notes' => ['top' => 'シトラス、ベリー', 'middle' => 'フローラル、フルーティ', 'base' => 'ムスク、ウッディ'], 'variants' => [['sku' => 'AS-LW-30', 'size_ml' => 30, 'price_yen' => 5610, 'concentration' => 'EDT']]],
            ['brand_name' => 'アナスイ', 'category_name' => 'フローラル EDT', 'name' => 'ファンタジア オードトワレ', 'gender' => 'women', 'short_desc' => 'ユニコーンが舞うファンタジックな世界。甘くロマンティックな香り。', 'long_desc' => '魔法のようなファンタジーの世界へ誘う「ファンタジア」。2017 年に発売された、甘くシトラスの香り。トップノートはポンメロとピンクペッパーで爽やかに香り立ち、ミドルノートではプラリネ、ラズベリー、フローラルノートが華やかに広がります。ベースノートではサイプレスとヒマラヤンシダーが温かみと深みを加えます。日常にファンタジーのタッチを大切にする方へ最適な、enchanting なフレグランスです。', 'notes' => ['top' => 'ピンクペッパー、柚子', 'middle' => 'バラのプリザーブ、ラズベリー', 'base' => 'ヒノキ、ゴールデンアンバー'], 'variants' => [['sku' => 'AS-FAN-30', 'size_ml' => 30, 'price_yen' => 5830, 'concentration' => 'EDT'], ['sku' => 'AS-FAN-75', 'size_ml' => 75, 'price_yen' => 10450, 'concentration' => 'EDT']]],
            ['brand_name' => 'アナスイ', 'category_name' => 'フローラル EDT', 'name' => 'ファンタジア マーメイド オードトワレ', 'gender' => 'women', 'short_desc' => 'マーメイドの世界観を表現した、マリンでフルーティな香り。', 'long_desc' => 'マーメイドの世界観を表現した、マリンでフルーティな「ファンタジア マーメイド」。トップノートはカルダモン、ブラッドオレンジ、マンダリンオレンジで爽やかに香り立ちます。ミドルノートではライチ、ジャスミン、ピオニーが女性的な魅力を広げます。ベースノートではハニー、バニラ、ホワイトウッドが甘く優しい余韻を残します。うっとりとするようなフロリエンタル調のブーケに、フルーティーさとスパイスが加わった甘い誘惑の香りです。', 'notes' => ['top' => 'シトラス、ブラッドオレンジ', 'middle' => 'スイートピー、ジャスミン', 'base' => 'バニラ、ウッディ'], 'variants' => [['sku' => 'AS-FANM-30', 'size_ml' => 30, 'price_yen' => 5830, 'concentration' => 'EDT']]],
            ['brand_name' => 'アナスイ', 'category_name' => 'フローラル EDT', 'name' => 'スイドリームス オードトワレ', 'gender' => 'women', 'short_desc' => '夢見る少女のための、甘く幻想的な香り。', 'long_desc' => '夢見る少女のための、甘く幻想的な「スイ ドリームス」。2001 年に発売されたパウダリーでスイートなフレグランス。トップノートはネクタリン、マンダリンオレンジ、ビターオレンジ、ベルガモットが爽やかに香り立ちます。ハートノートではピーチ、フリージア、チャイニーズピオニー、ローズがフローラルフルーティな広がりを。ベースノートではタヒチアンバニラ、ナツメグ、ムスク、アニス、サンダルウッド、シダーが温かみのあるベースを形成します。', 'notes' => ['top' => 'フルーティ、シトラス', 'middle' => 'フローラル、スウィート', 'base' => 'ムスク、バニラ'], 'variants' => [['sku' => 'AS-SD-30', 'size_ml' => 30, 'price_yen' => 5830, 'concentration' => 'EDT']]],
            ['brand_name' => 'アナスイ', 'category_name' => 'フローラル EDT', 'name' => 'フライト オブ ファンシー オードトワレ', 'gender' => 'women', 'short_desc' => '自由な発想と冒険を表現した、エキゾチックな香り。', 'long_desc' => '自由な発想と冒険を表現した「フライト オブ ファンシー」。トップノートはライチ、ユズ、ジャバレモンが爽やかに香り立ちます。ミドルノートではパープルレインフリージア、ローズブロッサム、スターマグノリアが華やかに広がります。ベースノートではスキンムスク、ホワイトウッド、アンバークリスタル、ベンゾインが複雑で重層的な香りを形成し、平和と静けさをもたらします。', 'notes' => ['top' => 'ライチ、ユズ', 'middle' => 'マグノリア、フリージア', 'base' => 'アンバー、ムスク'], 'variants' => [['sku' => 'AS-FOF-30', 'size_ml' => 30, 'price_yen' => 5500, 'concentration' => 'EDT']]],
        ];
    }

    // === PAUL & JOE (6 products) ===
    private function getPaulJoeProducts(): array
    {
        return [
            ['brand_name' => 'ポール＆ジョー', 'category_name' => 'フローラル EDT', 'name' => 'ブルー オードトワレ', 'gender' => 'women', 'short_desc' => 'デザイナー・ソフィーの愛猫ジプシーをイメージした、フレッシュでクリーンな香り。', 'long_desc' => 'デザイナー・ソフィーの愛猫ジプシーをイメージした、フレッシュでクリーンな「ブルー」。洗練された大人の女性に向けて、装いを一新して登場。健康的なセクシーさと好奇心あふれる力強さが魅力。いきいきとしてカリスマティックでフェミニンなオリエンタルムスキー＆フローラルフレグランスです。シトラスとグリーンノートのトップから、フローラルとフリージアのミドルへ。ムスクとシダーの清潔感のあるベース。', 'notes' => ['top' => 'シトラス、グリーンノート', 'middle' => 'フローラル、フリージア', 'base' => 'ムスク、シダー'], 'variants' => [['sku' => 'PJ-BLUE-50', 'size_ml' => 50, 'price_yen' => 6600, 'concentration' => 'EDT']]],
            ['brand_name' => 'ポール＆ジョー', 'category_name' => 'フローラル EDT', 'name' => 'ブラン オードトワレ', 'gender' => 'women', 'short_desc' => '純白で優しいイメージのフローラルムスキー。', 'long_desc' => '純白で優しいイメージのフローラルムスキー「ブラン」。ロマンティックでナチュラルな気分になれる香り。花束を抱きしめたかのようなピュアでイノセントな香りで、フレッシュなすがすがしさとほのかな甘さが心地よいトップノートが特徴です。サンザシ、アンゼリカのトップから、ジャスミンとホワイトローズのミドルへ。ホワイトムスクとサンダルウッドのやさしいベース。', 'notes' => ['top' => 'シトラス、ホワイトティー', 'middle' => 'ジャスミン、ホワイトローズ', 'base' => 'ホワイトムスク、サンダルウッド'], 'variants' => [['sku' => 'PJ-BLANC-50', 'size_ml' => 50, 'price_yen' => 6600, 'concentration' => 'EDT']]],
            ['brand_name' => 'ポール＆ジョー', 'category_name' => 'フローラル EDT', 'name' => 'ローズ オードトワレ', 'gender' => 'women', 'short_desc' => '華やかでロマンティックなバラの香り。', 'long_desc' => '華やかでロマンティックなバラの香り「ローズ」。ピンクペッパーとベリーのトップから、ダマスクローズとピオニーのフローラルミドルへ。アンバーとムスクの温かみのあるベース。女の子らしい甘くロマンティックなフレグランスで、つぼみから満開を迎えるように大きく花開くローズの香りが特徴です。', 'notes' => ['top' => 'ピンクペッパー、ベリー', 'middle' => 'ダマスクローズ、ピオニー', 'base' => 'アンバー、ムスク'], 'variants' => [['sku' => 'PJ-ROSE-50', 'size_ml' => 50, 'price_yen' => 6600, 'concentration' => 'EDT']]],
            ['brand_name' => 'ポール＆ジョー', 'category_name' => 'ボディミスト', 'name' => 'リフレッシング ミスト', 'gender' => 'women', 'short_desc' => 'さっぱりとした使用感のボディミスト。', 'long_desc' => 'さっぱりとした使用感のボディミスト「リフレッシング ミスト」。お気に入りの香りを楽しみながら心地よくうるおいを与えるミストタイプの全身（フェイス、ボディ、ヘア）用化粧水。きめ細かなミストに包まれて身体いっぱいに心地よい香りとみずみずしいうるおいを纏います。トップ：シトラス（ベルガモット、オレンジ、マンダリン）、フルーティ（ブラックカラント、ライチ、ペア）、グリーン。ミドル：フローラル（サクラ、スズラン、マグノリア）。', 'notes' => ['top' => 'シトラス、ミント', 'middle' => 'フローラル、グリーン', 'base' => 'ムスク'], 'variants' => [['sku' => 'PJ-MIST-100', 'size_ml' => 100, 'price_yen' => 3850, 'concentration' => 'Mist']]],
            ['brand_name' => 'ポール＆ジョー', 'category_name' => 'ヘアミスト', 'name' => 'ヘア＆ボディ ミスト', 'gender' => 'women', 'short_desc' => '髪にも使えるフレグランスミスト。', 'long_desc' => '髪にも使えるフレグランスミスト「ヘア＆ボディ ミスト」。うるおいと心地よいオレンジフラワーの香りをボディやヘアに纏わせる、ミストタイプの化粧水。保湿成分配合のキメ細かなミストが、ボディと髪を心地よく包みこみ、爽やかな女性らしさの中にもやや苦味を含み、大人の女性にぴったりのオレンジフラワーの香りをまとえます。', 'notes' => ['top' => 'シトラス、フルーティ', 'middle' => 'フローラル', 'base' => 'ムスク'], 'variants' => [['sku' => 'PJ-HM-100', 'size_ml' => 100, 'price_yen' => 4400, 'concentration' => 'Mist']]],
            ['brand_name' => 'ポール＆ジョー', 'category_name' => 'フローラル EDT', 'name' => 'オレンジブロッサム オードトワレ', 'gender' => 'women', 'short_desc' => 'オレンジの花の爽やかで甘い香り。', 'long_desc' => 'オレンジの花の爽やかで甘い香り「オレンジブロッサム」。爽やかなマンダリンとレモンのシトラスから、オレンジの花、ライラック、ジャスミンの可憐で無邪気なフローラルへと変化します。かすかに残るバニラムスクがやさしい余韻を残します。シャワーのような爽やかさと、花々の優しさが調和した、ピュアでイノセントなフレグランスです。', 'notes' => ['top' => 'オレンジ、ネロリ', 'middle' => 'オレンジブロッサム、ジャスミン', 'base' => 'ムスク、バニラ'], 'variants' => [['sku' => 'PJ-OB-50', 'size_ml' => 50, 'price_yen' => 6600, 'concentration' => 'EDT']]],
        ];
    }

    // === JILL STUART (6 products) ===
    private function getJillStuartProducts(): array
    {
        return [
            ['brand_name' => 'ジルスチュアート', 'category_name' => 'フローラル EDP', 'name' => 'ホワイトフローラル オードトワレ', 'gender' => 'women', 'short_desc' => '純白の花束のようなピュアでロマンティックな香り。', 'long_desc' => '純白の花のブーケのようにピュアでロマンティックな香りが、軽やかに香り立つ「ホワイトフローラル」。幸福感に満たされ心落ち着くロマンティックなひとときへ。トップノートはピーチ、ストロベリー、ラズベリーなどのフルーティ。ミドルノートはリリー、ミュゲ、オレンジフラワーなどのフローラル。ラストノートはセダーウッド、ベチバーなどのウッディムスク。ころんとしたボディにリボンがモチーフの装飾を施した、可憐なボトルデザイン。', 'notes' => ['top' => 'ピーチ、ストロベリー', 'middle' => 'リリー、ミュゲ', 'base' => 'ホワイトムスク、サンダルウッド'], 'featured' => true, 'variants' => [['sku' => 'JS-WF-10', 'size_ml' => 10, 'price_yen' => 2200, 'concentration' => 'EDT'], ['sku' => 'JS-WF-50', 'size_ml' => 50, 'price_yen' => 4400, 'concentration' => 'EDT']]],
            ['brand_name' => 'ジルスチュアート', 'category_name' => 'フローラル EDP', 'name' => 'クリスタルブルーム オードパルファン', 'gender' => 'women', 'short_desc' => 'クリスタルのように輝く花々のブーケ。華やかで上品な香り。', 'long_desc' => 'クリスタルピュアフローラルノート「クリスタルブルーム」。世界調香師クリスティーヌ・ナゲル氏によって調香された、透明感あるフローラルフレグランス。トップ：スイートピー、スノードロップ、ネロリ、オレンジ、グリーン。ミドル：エーデルワイス、マグノリア、ローズ、フリージア、ジャスミン、ラズベリー。ベース：チュールアコード、オスマンサス、ガーデニア、イランイラン、モス、シダーウッド、ムスク、アンバー。儚げながらも豊かな広がりを見せる、可憐な花々をちりばめた香り。', 'notes' => ['top' => 'シトラス、フルーツ', 'middle' => 'ローズ、ジャスミン、フリージア', 'base' => 'ムスク、サンダルウッド'], 'variants' => [['sku' => 'JS-CB-30', 'size_ml' => 30, 'price_yen' => 6490, 'concentration' => 'EDP']]],
            ['brand_name' => 'ジルスチュアート', 'category_name' => 'フローラル EDP', 'name' => 'ブリリアントジュエル オードパルファン', 'gender' => 'women', 'short_desc' => '宝石のように輝く女性のためのフレグランス。', 'long_desc' => '宝石のように輝く女性のための「ブリリアントジュエル」。2020 年発売。甘く柔らかい「光」の香りに、輝く太陽を浴びた果実のノートと 7 つの花々の重なり合う香りを組み合わせました。トップノート：ベルガモット、レモン、オレンジ、ピンクペッパー、バイオレット、パイナップル、カシス。ミドルノート：ローズ、オスマンサス、ミモザ、ローズマリー、ラベンダー、アイリス、パチュリ、オレンジフラワー、ジャスミン。ベースノート：ムスク、アンバー、サンダルウッド。', 'notes' => ['top' => 'ベリー、シトラス', 'middle' => 'ローズ、ジャスミン', 'base' => 'アンバー、ムスク'], 'variants' => [['sku' => 'JS-BJ-30', 'size_ml' => 30, 'price_yen' => 6490, 'concentration' => 'EDP'], ['sku' => 'JS-BJ-50', 'size_ml' => 50, 'price_yen' => 9130, 'concentration' => 'EDP']]],
            ['brand_name' => 'ジルスチュアート', 'category_name' => 'フローラル EDP', 'name' => 'サクラブーケ オードパルファン', 'gender' => 'women', 'short_desc' => '春の桜の花束をイメージした限定フレグランス。', 'long_desc' => '春の桜の花束をイメージした限定フレグランス「サクラブーケ」。今年のテーマは、川面を八重桜の花びらで満たす情景。水面に桜の花びらが積もる情景を表現した限定の香り。清潔感あるし、癖がない。好印象を与える女の子らしいフローラル系の香り。サクラとフルーツのトップから、ローズとジャスミンのフローラルミドルへ。ムスクとサンダルウッドのベース。', 'notes' => ['top' => 'サクラ、フルーツ', 'middle' => 'ローズ、ジャスミン', 'base' => 'ムスク、サンダルウッド'], 'variants' => [['sku' => 'JS-SAK-30', 'size_ml' => 30, 'price_yen' => 6490, 'concentration' => 'EDP']]],
            ['brand_name' => 'ジルスチュアート', 'category_name' => 'ヘアミスト', 'name' => 'ホワイトフローラル ヘアミスト', 'gender' => 'women', 'short_desc' => '髪に香りを纏うヘアミスト。', 'long_desc' => '髪に香りを纏うヘアミスト「ホワイトフローラル ヘアミスト」。ふんわりと香りながら、指通りをなめらかにするヘアミスト。キューティクル補修成分（ヒアルロン酸誘導体）が、浮き上がってめくれてしまったキューティクルを補修。純白な花のブーケのよう。ピュアで甘く、無垢な気持ちに包み込まれるような幸福感。どんなときも心を落ち着かせ、素直な気持ちに。ピーチ、ベリーのトップから、ホワイトフローラルのミドルへ。ムスクのベース。', 'notes' => ['top' => 'ピーチ、ベリー', 'middle' => 'ホワイトフローラル', 'base' => 'ムスク'], 'variants' => [['sku' => 'JS-WF-HM-200', 'size_ml' => 200, 'price_yen' => 3080, 'concentration' => 'Mist']]],
            ['brand_name' => 'ジルスチュアート', 'category_name' => 'フローラル EDP', 'name' => 'ピーチーホワイトフローラル オードトワレ', 'gender' => 'women', 'short_desc' => 'みずみずしく甘いピーチと白い花の香り。限定品。', 'long_desc' => 'みずみずしく甘いピーチと白い花の香り「ピーチーホワイトフローラル」。限定品。純白のブーケのようなホワイトフローラルと、愛らしさ溢れるピーチやベリーが折り重なり、甘くとろけるように香るオードトワレ。うるおいと甘美な香りが持続。みずみずしく甘い「ホワイトフローラル」をベースに、果実感溢れる甘酸っぱいピーチやベリーを加えた、甘美なひと時へと誘う甘くとろけるような香り。', 'notes' => ['top' => 'ピーチ、ベリー', 'middle' => 'ホワイトフローラル', 'base' => 'ムスク、バニラ'], 'variants' => [['sku' => 'JS-PWF-50', 'size_ml' => 50, 'price_yen' => 4400, 'concentration' => 'EDT']]],
        ];
    }

    // === EXCEL (6 products) ===
    private function getExcelProducts(): array
    {
        return [
            ['brand_name' => 'エクセル', 'category_name' => 'ボディミスト', 'name' => 'フレグランスボディミスト ホワイトティー', 'gender' => 'women', 'short_desc' => 'プチプラながら高品質なボディミスト。白茶の香り。', 'long_desc' => 'プチプラながら高品質なボディミスト「フレグランスボディミスト ホワイトティー」。午後 3 時、優しい日差しの中でアフタヌーンティーを楽しむようなイメージ。爽やかな柑橘が、柔らかく香る茶葉とブレンドされ、優しいホワイトティーの香りに。トップ：ベルガモット、レモン。ミドル：ティー、ジャスミン、ローズ。ベース：ムスク、シダーウッド。軽やかなホワイトティーと爽やかなベルガモットの開放感あふれる透き通った香り。', 'notes' => ['top' => 'シトラス、グリーン', 'middle' => 'ホワイトティー、フローラル', 'base' => 'ムスク'], 'variants' => [['sku' => 'EX-WTM-100', 'size_ml' => 100, 'price_yen' => 1430, 'concentration' => 'Mist']]],
            ['brand_name' => 'エクセル', 'category_name' => 'ボディミスト', 'name' => 'フレグランスボディミスト サボン', 'gender' => 'unisex', 'short_desc' => '清潔感のある石鹸の香り。', 'long_desc' => '清潔感のある石鹸の香り「フレグランスボディミスト サボン」。爽やかで軽やかなサボンフレッシュの香り。レモンとオレンジのシトラストップから、ローズとフローラルのミドルへ。ムスクの清潔感のあるベース。天然エッセンシャルオイル成分配合。毎日使えるお手頃価格ながら、高品質な香りが特徴。', 'notes' => ['top' => 'レモン、オレンジ', 'middle' => 'ローズ、フローラル', 'base' => 'ムスク'], 'variants' => [['sku' => 'EX-SVM-100', 'size_ml' => 100, 'price_yen' => 1430, 'concentration' => 'Mist']]],
            ['brand_name' => 'エクセル', 'category_name' => 'ボディミスト', 'name' => 'フレグランスヘアミスト', 'gender' => 'women', 'short_desc' => '髪に使えるフレグランスミスト。', 'long_desc' => '髪に使えるフレグランスミスト「フレグランスヘアミスト」。フルーティとシトラスのトップから、フローラルのミドルノートへ。ムスクのやさしいベース。髪にやさしい処方の軽やかなミスト。天然エッセンシャルオイル配合で、香りとともに髪をケア。', 'notes' => ['top' => 'フルーティ、シトラス', 'middle' => 'フローラル', 'base' => 'ムスク'], 'variants' => [['sku' => 'EX-HM-80', 'size_ml' => 80, 'price_yen' => 1540, 'concentration' => 'Mist']]],
            ['brand_name' => 'エクセル', 'category_name' => 'パルファムオイル', 'name' => 'フレグランスオイル ローズ', 'gender' => 'women', 'short_desc' => '練り香水タイプのフレグランスオイル。', 'long_desc' => '練り香水タイプのフレグランスオイル「フレグランスオイル ローズ」。セントフォリアローズをベースとした、ロマンティックな香り。ローズの優しい香りが、ここちよい優雅な時間を演出。フルーツのトップから、ローズのフローラルミドルへ。ムスクのベース。持ち運びに便利な練り香水タイプ。', 'notes' => ['top' => 'フルーツ', 'middle' => 'ローズ', 'base' => 'ムスク'], 'variants' => [['sku' => 'EX-OIL-10', 'size_ml' => 10, 'price_yen' => 1100, 'concentration' => 'Oil']]],
            ['brand_name' => 'エクセル', 'category_name' => 'パルファムオイル', 'name' => 'フレグランスオイル ジャスミン', 'gender' => 'women', 'short_desc' => '練り香水タイプのフレグランスオイル。', 'long_desc' => '練り香水タイプのフレグランスオイル「フレグランスオイル ジャスミン」。華やかなジャスミンの香り。軽めで芳しい、そしてフローラルなジャスミンの香り。シトラスのトップから、ジャスミンのフローラルミドルへ。ムスクのベース。持ち運びに便利な練り香水タイプ。', 'notes' => ['top' => 'シトラス', 'middle' => 'ジャスミン', 'base' => 'ムスク'], 'variants' => [['sku' => 'EX-OIL-J-10', 'size_ml' => 10, 'price_yen' => 1100, 'concentration' => 'Oil']]],
            ['brand_name' => 'エクセル', 'category_name' => 'ボディミスト', 'name' => 'フレグランスボディミスト ベリー', 'gender' => 'women', 'short_desc' => '甘いベリーの香り。', 'long_desc' => '甘いベリーの香り「フレグランスボディミスト ベリー」。ほどよく香る、どんなシーンでも使えるフレグランスボディミスト。甘酸っぱいベリーがあふれだす、みずみずしい香り。ストロベリーとラズベリーのフルーティトップから、フローラルのミドルノートへ。バニラのスイートなベース。', 'notes' => ['top' => 'ストロベリー、ラズベリー', 'middle' => 'フローラル', 'base' => 'バニラ'], 'variants' => [['sku' => 'EX-BM-100', 'size_ml' => 100, 'price_yen' => 1430, 'concentration' => 'Mist']]],
        ];
    }

    // === CHANEL (6 products) ===
    private function getChanelProducts(): array
    {
        return [
            ['brand_name' => 'シャネル', 'category_name' => 'フローラル EDP', 'name' => 'シャネル N°5 オードパルファム', 'gender' => 'women', 'short_desc' => '1921年に誕生した永遠の名作。アルデヒドとフラワーの調和が生み出す不朽のフレグランス。', 'notes' => ['top' => 'アルデヒド、イランイラン', 'middle' => 'ジャスミン、ローズ', 'base' => 'サンダルウッド、バニラ'], 'featured' => true, 'variants' => [['sku' => 'CH-N5-EDP-35', 'size_ml' => 35, 'price_yen' => 13200, 'concentration' => 'EDP'], ['sku' => 'CH-N5-EDP-50', 'size_ml' => 50, 'price_yen' => 18700, 'concentration' => 'EDP'], ['sku' => 'CH-N5-EDP-100', 'size_ml' => 100, 'price_yen' => 26400, 'concentration' => 'EDP']]],
            ['brand_name' => 'シャネル', 'category_name' => 'フレッシュ EDT', 'name' => 'シャネル N°5 ロー オードトワレ', 'gender' => 'women', 'short_desc' => 'N°5のモダンな解釈。軽やかでフレッシュな印象。', 'long_desc' => 'N°5 のモダンな解釈。軽やかでフレッシュな印象。ネロリの爽やかなトップから、ジャスミン、ローズ、イランイランの花々のミドルノートへ。シダーとムスクの清潔感のあるベース。伝説的な N°5 を現代的にアレンジした、日常使いしやすいフレグランス。洋梨の爽やかさとフリージアの優しい香りが合わさって、甘すぎずくどくない、心地よい香り。', 'notes' => ['top' => 'シトラス、アルデヒド', 'middle' => 'ジャスミン、ローズ', 'base' => 'シダー、ムスク'], 'variants' => [['sku' => 'CH-N5L-EDT-50', 'size_ml' => 50, 'price_yen' => 15400, 'concentration' => 'EDT'], ['sku' => 'CH-N5L-EDT-100', 'size_ml' => 100, 'price_yen' => 22000, 'concentration' => 'EDT']]],
            ['brand_name' => 'シャネル', 'category_name' => 'オリエンタル EDP', 'name' => 'ココ マドモアゼル オードパルファム', 'gender' => 'women', 'short_desc' => 'モダンで大胆な女性のためのフレグランス。', 'long_desc' => '大胆で自由な女性のための「ココ マドモアゼル」。オリエンタルアンバーフレグランス。鮮やかで生き生きとしたオレンジのスパークスが、ジャスミンとローズのアコードを明るく照らし、パチュリとベチバーのヒントで強調されます。トップ：オレンジ、ベルガモット。ミドル：ジャスミン、ローズ。ベース：パチュリ、ベチバー、トンカ、バニラ。官能的で大胆な、現代的な女性の象徴となるフレグランス。', 'notes' => ['top' => 'オレンジ、ベルガモット', 'middle' => 'ジャスミン、ローズ', 'base' => 'パチュリ、ベチバー'], 'featured' => true, 'variants' => [['sku' => 'CH-CM-EDP-35', 'size_ml' => 35, 'price_yen' => 14850, 'concentration' => 'EDP'], ['sku' => 'CH-CM-EDP-50', 'size_ml' => 50, 'price_yen' => 20900, 'concentration' => 'EDP'], ['sku' => 'CH-CM-EDP-100', 'size_ml' => 100, 'price_yen' => 29700, 'concentration' => 'EDP']]],
            ['brand_name' => 'シャネル', 'category_name' => 'フローラル EDP', 'name' => 'チャンス オー タンドゥル オードパルファム', 'gender' => 'women', 'short_desc' => 'やわらかくフェミニンな香り。', 'long_desc' => 'フローラルフルーティの香り「チャンス オー タンドゥル」。2019 年発売。あなたのユニークなパーソナリティを表現する香り。純粋な女性のためのフローラルフルーティフレグランスが、優しさの波で空間を満たします。トップ：グレープフルーツ、カリン。ミドル：ジャスミン、ヒヤシンス。ベース：ムスク、アイリス、シダーウッド、アンバー。日常使いに最適で、あらゆる機会にエレガント。', 'notes' => ['top' => 'グレープフルーツ、キンポウゲ', 'middle' => 'ヒヤシンス、ジャスミン', 'base' => 'アンバー、ムスク'], 'variants' => [['sku' => 'CH-CHT-EDP-50', 'size_ml' => 50, 'price_yen' => 18150, 'concentration' => 'EDP'], ['sku' => 'CH-CHT-EDP-100', 'size_ml' => 100, 'price_yen' => 26400, 'concentration' => 'EDP']]],
            ['brand_name' => 'シャネル', 'category_name' => 'フレッシュ EDT', 'name' => 'ブルー ドゥ シャネル オードトワレ', 'gender' => 'men', 'short_desc' => '自由で野性的な男性のためのフレグランス。', 'long_desc' => '自由で野性的な男性のための「ブルー ドゥ シャネル」。アロマティックウッディフレグランス。ニューカレドニア産サンダルウッドが、シダーのドライなささやきと、シトラスの活気と出会います。トップ：グレープフルーツ、レモン、ミント、ピンクペッパー。ミドル：ジンジャー、イソノーム、ジャスミン、ラベンダー。ベース：インセンス、シダー、サンダルウッド、パチュリ、ラバナム、ベチバー。爽やかなシトラスと暖かいウッディノートの調和。', 'notes' => ['top' => 'シトラス、ペッパー', 'middle' => 'ミント、ジャスミン', 'base' => 'シダー、サンダルウッド'], 'featured' => true, 'variants' => [['sku' => 'CH-BDC-EDT-50', 'size_ml' => 50, 'price_yen' => 13200, 'concentration' => 'EDT'], ['sku' => 'CH-BDC-EDT-100', 'size_ml' => 100, 'price_yen' => 18700, 'concentration' => 'EDT'], ['sku' => 'CH-BDC-EDT-150', 'size_ml' => 150, 'price_yen' => 24200, 'concentration' => 'EDT']]],
            ['brand_name' => 'シャネル', 'category_name' => 'ウッディ EDP', 'name' => 'ブルー ドゥ シャネル オードパルファム', 'gender' => 'men', 'short_desc' => 'より深みのあるブルー ドゥ シャネル。', 'long_desc' => 'より深みのある「ブルー ドゥ シャネル オードパルファム」。センシュアルなアンバーと柔らかなムスクが合わさったエレガントな アロマティック ウッディ フレグランス。トップ：シトラス、ミント。ミドル：ペッパー、ジャスミン。ベース：インセンス、シダー、サンダルウッド、パチュリ。ブルーのボトルに入った、時代を超越した香り。強い意志のある洗練されたエレガンスを映し出します。', 'notes' => ['top' => 'シトラス、ミント', 'middle' => 'ペッパー、ジャスミン', 'base' => 'インセンス、シダー'], 'variants' => [['sku' => 'CH-BDC-EDP-50', 'size_ml' => 50, 'price_yen' => 15400, 'concentration' => 'EDP'], ['sku' => 'CH-BDC-EDP-100', 'size_ml' => 100, 'price_yen' => 22000, 'concentration' => 'EDP']]],
        ];
    }

    // === DIOR (6 products) ===
    private function getDiorProducts(): array
    {
        return [
            ['brand_name' => 'ディオール', 'category_name' => 'フローラル EDP', 'name' => 'ジャドール オードパルファム', 'gender' => 'women', 'short_desc' => '華やかでフェミニンなフローラルの香り。現代的な女性の象徴。', 'notes' => ['top' => 'ペア、メロン、ベルガモット', 'middle' => 'ジャスミン、ローズ、リリー', 'base' => 'バニラ、ムスク、シダー'], 'featured' => true, 'variants' => [['sku' => 'DI-JAD-30', 'size_ml' => 30, 'price_yen' => 11000, 'concentration' => 'EDP'], ['sku' => 'DI-JAD-50', 'size_ml' => 50, 'price_yen' => 16500, 'concentration' => 'EDP'], ['sku' => 'DI-JAD-100', 'size_ml' => 100, 'price_yen' => 24200, 'concentration' => 'EDP']]],
            ['brand_name' => 'ディオール', 'category_name' => 'フローラル EDP', 'name' => 'ミス ディオール オードパルファム', 'gender' => 'women', 'short_desc' => '優雅でロマンティックなフローラルの香り。', 'long_desc' => 'リニューアル発売。まるで花びらのようになめらかで、森の下草のようにみずみずしい、官能的で包み込むようなサプライズをも与えるフレグランス。きりりとフレッシュなシトラス、甘く重厚に香る最高級のエジプト産ジャスミン、丁寧に手摘みされた華やかなグラース産ローズのハーモニー。アイリスとピオニーの優雅なトップから、スズランとローズの愛らしいミドルへ。ムスクとバニラのやさしいベース。', 'notes' => ['top' => 'アイリス、ピオニー', 'middle' => 'スズラン、ローズ', 'base' => 'ムスク、バニラ'], 'featured' => true, 'variants' => [['sku' => 'DI-MD-30', 'size_ml' => 30, 'price_yen' => 11000, 'concentration' => 'EDP'], ['sku' => 'DI-MD-50', 'size_ml' => 50, 'price_yen' => 16500, 'concentration' => 'EDP'], ['sku' => 'DI-MD-100', 'size_ml' => 100, 'price_yen' => 24200, 'concentration' => 'EDP']]],
            ['brand_name' => 'ディオール', 'category_name' => 'フレッシュ EDT', 'name' => 'ソヴァージュ オードトワレ', 'gender' => 'men', 'short_desc' => '野性味あふれる男性のためのフレグランス。', 'notes' => ['top' => 'ベルガモット、ペッパー', 'middle' => 'ラベンダー、パチュリ', 'base' => 'アンブロキサン、シダー'], 'featured' => true, 'variants' => [['sku' => 'DI-SAU-60', 'size_ml' => 60, 'price_yen' => 12100, 'concentration' => 'EDT'], ['sku' => 'DI-SAU-100', 'size_ml' => 100, 'price_yen' => 15400, 'concentration' => 'EDT'], ['sku' => 'DI-SAU-200', 'size_ml' => 200, 'price_yen' => 21450, 'concentration' => 'EDT']]],
            ['brand_name' => 'ディオール', 'category_name' => 'ウッディ EDP', 'name' => 'ソヴァージュ オードパルファム', 'gender' => 'men', 'short_desc' => 'より深みのあるソヴァージュ。', 'long_desc' => '2018 年 7 月 27 日よりディオール公式オンラインブティックにて先行発売。スパイシーな爽やかさの中にセンシュアルな甘さが漂うフレグランス。みずみずしくもほろ苦いカラブリアンベルガモットが、パプアニューギニア産バニラに包まれた神秘的な香り。力強くも気高い香りの男性用フレグランス。', 'notes' => ['top' => 'ベルガモット、ペッパー', 'middle' => 'ラベンダー、バニラ', 'base' => 'ナツメグ、アンバー'], 'variants' => [['sku' => 'DI-SAU-EDP-60', 'size_ml' => 60, 'price_yen' => 14300, 'concentration' => 'EDP'], ['sku' => 'DI-SAU-EDP-100', 'size_ml' => 100, 'price_yen' => 19800, 'concentration' => 'EDP']]],
            ['brand_name' => 'ディオール', 'category_name' => 'オリエンタル EDP', 'name' => 'ソヴァージュ エリクシール', 'gender' => 'men', 'short_desc' => 'ソヴァージュの最も濃厚な表現。', 'long_desc' => '国内未発売のソヴァージュエリクシールは上質なリキュールのような香水。フレッシュなラベンダーやウッディな甘い香り、グレープフルーツのスパイスが香ります。「ソヴァージュ・エリクシール」の香りは、アロマティック・フゼアの香調がベース。ダンディーなテイストに仕上げられております。ニヨン産ラベンダー・エッセンス、濃縮されたフレグランス。', 'notes' => ['top' => 'グレープフルーツ、シナモン', 'middle' => 'ラベンダー、リコリス', 'base' => 'バニラ、サンダルウッド'], 'variants' => [['sku' => 'DI-SAU-EL-60', 'size_ml' => 60, 'price_yen' => 17600, 'concentration' => 'Parfum']]],
            ['brand_name' => 'ディオール', 'category_name' => 'フローラル EDP', 'name' => 'プワゾン ガール オードパルファム', 'gender' => 'women', 'short_desc' => '甘く魅惑的な香り。', 'long_desc' => '店舗限定発売。ビターオレンジの香りとベネズエラ産トンカビーンが甘美な官能性をグラース産ローズの香りと調和させたフレグランス。プワゾン ガールは、自由でセクシーな現代の女の子のフレグランス。一瞬で惑わし、ずっと続く喜びで虜にする甘い罠。ベネズエラ産トンカビーンにふんわりと包まれた、甘く魅惑的な香り。', 'notes' => ['top' => 'ビターオレンジ、レモン', 'middle' => 'ローズ、オレンジブロッサム', 'base' => 'バニラ、トンカ、アーモンド'], 'variants' => [['sku' => 'DI-PG-30', 'size_ml' => 30, 'price_yen' => 11000, 'concentration' => 'EDP'], ['sku' => 'DI-PG-50', 'size_ml' => 50, 'price_yen' => 15950, 'concentration' => 'EDP']]],
        ];
    }

    // === TOM FORD (6 products) ===
    private function getTomFordProducts(): array
    {
        return [
            ['brand_name' => 'トムフォード', 'category_name' => 'ウッディ EDP', 'name' => 'ウードウッド オードパルファム', 'gender' => 'unisex', 'short_desc' => '高級ウードウッドとアンバーの調和。東洋的な魅力。', 'long_desc' => '高級ウードウッドとアンバーの調和「ウードウッド」。2007 年発売。最も高価で希少なウードウッド、エキゾチックなスパイス、ローズウッド、カルダモンをブレンドした、画期的なウッディフレグランス。トップノート：ローズウッド、カルダモン。ミドルノート：ウードウッド、サンダルウッド、ベチバー。ベースノート：トンカビーン、アンバー。中東の伝統を現代的に解釈した、官能的で神秘的な香り。', 'notes' => ['top' => 'ローズウッド、カルダモン', 'middle' => 'ウード、サンダルウッド', 'base' => 'アンバー、バニラ、トンカ'], 'featured' => true, 'variants' => [['sku' => 'TF-OW-30', 'size_ml' => 30, 'price_yen' => 23100, 'concentration' => 'EDP'], ['sku' => 'TF-OW-50', 'size_ml' => 50, 'price_yen' => 34650, 'concentration' => 'EDP'], ['sku' => 'TF-OW-100', 'size_ml' => 100, 'price_yen' => 49500, 'concentration' => 'EDP']]],
            ['brand_name' => 'トムフォード', 'category_name' => 'オリエンタル EDP', 'name' => 'タバコバニラ オードパルファム', 'gender' => 'unisex', 'short_desc' => 'タバコとバニラの魅惑的な組み合わせ。', 'long_desc' => 'タバコとバニラの魅惑的な組み合わせ「タバコバニラ」。ロンドンに対するトム フォードの思慕が、スパイスやコニャックの芳醇な香り漂う、イギリスの紳士クラブを思わせるこのフレグランスを誕生させました。トップノート：タバコリーフ、ジンジャー、スパイス。ミドルノート：トンカビーン、ココア、ドライフルーツ。ベースノート：バニラ、スイートウッドサップ。大人の色気と渋さも感じる、豊かで官能的な香り。', 'notes' => ['top' => 'タバコリーフ、ジンジャー', 'middle' => 'トンカ、ココア', 'base' => 'バニラ、ドライフルーツ'], 'variants' => [['sku' => 'TF-TV-50', 'size_ml' => 50, 'price_yen' => 39600, 'concentration' => 'EDP'], ['sku' => 'TF-TV-100', 'size_ml' => 100, 'price_yen' => 58850, 'concentration' => 'EDP']]],
            ['brand_name' => 'トムフォード', 'category_name' => 'フローラル EDP', 'name' => 'ブラックオーキッド オードパルファム', 'gender' => 'women', 'short_desc' => '神秘的で官能的なオーキッドの香り。', 'long_desc' => '神秘的で官能的なオーキッドの香り「ブラックオーキッド」。2006 年発売。モダンであるとともに永遠に引き継がれるフラグランス。リッチ ダーク アコードに魅惑的なアクセントとしてブラック オーキッドを加え、スパイスをほんの少し効かせたラグジュアリーでセンシュアスな香り。トップノート：トリュフ、ブラックプラム、ベルガモット。ミドルノート：ブラックオーキッド、ジャスミン、ブラックプラム。ベースノート：バニラ、パチュリ、サンダルウッド、インセンス。', 'notes' => ['top' => 'トリュフ、ガーデニア', 'middle' => 'ブラックオーキッド、ジャスミン', 'base' => 'バニラ、パチュリ、サンダルウッド'], 'variants' => [['sku' => 'TF-BO-50', 'size_ml' => 50, 'price_yen' => 19800, 'concentration' => 'EDP'], ['sku' => 'TF-BO-100', 'size_ml' => 100, 'price_yen' => 28600, 'concentration' => 'EDP']]],
            ['brand_name' => 'トムフォード', 'category_name' => 'フルーティー EDP', 'name' => 'ロストチェリー オードパルファム', 'gender' => 'unisex', 'short_desc' => '甘く魅惑的なチェリーの香り。', 'long_desc' => '甘く魅惑的なチェリーの香り「ロストチェリー」。2018 年発売。トムフォード 1 番人気？の香り。和っぽい桜餅のような香りと甘酸っぱいチェリーの香り。クラシカルで官能的なチェリーのフレグランス。トップノート：ブラックチェリー、チェリーリキュール、ビターアーモンド。ミドルノート：サワークリー、ターキッシュローズ、ジャスミンサンバック。ベースノート：ローステッドトンカビーン、サンダルウッド、ベチバー、バニラ。', 'notes' => ['top' => 'チェリー、アーモンド、シナモン', 'middle' => 'ジャスミン、ローズ', 'base' => 'バニラ、トンカ、サンダルウッド'], 'variants' => [['sku' => 'TF-LC-50', 'size_ml' => 50, 'price_yen' => 39600, 'concentration' => 'EDP']]],
            ['brand_name' => 'トムフォード', 'category_name' => 'シトラス EDP', 'name' => 'ネロリポルトフィーノ オードパルファム', 'gender' => 'unisex', 'short_desc' => 'イタリアのリビエラを感じさせる爽やかな香り。', 'long_desc' => 'イタリアのリビエラを感じさせる爽やかな香り「ネロリポルトフィーノ」。2007 年発売。イタリアのリビエラ地方、そしてコバルトブルーの地中海にインスパイアされた瑞々しい香り。「ポルトフィーノは私を魅了し続けている特別な場所」。トップノート：ベルガモット、マンダリン、レモン、ネロリ。ミドルノート：ラベンダー、ローズマリー、ジャスミン、オレンジブロッサム。ベースノート：アンバー、ムスク、ウッド。', 'notes' => ['top' => 'ベルガモット、マンダリン、レモン', 'middle' => 'ネロリ、オレンジブロッサム', 'base' => 'アンバー、ムスク'], 'variants' => [['sku' => 'TF-NP-50', 'size_ml' => 50, 'price_yen' => 23100, 'concentration' => 'EDP'], ['sku' => 'TF-NP-100', 'size_ml' => 100, 'price_yen' => 34650, 'concentration' => 'EDP']]],
            ['brand_name' => 'トムフォード', 'category_name' => 'レザー EDP', 'name' => 'タスカンレザー オードパルファム', 'gender' => 'unisex', 'short_desc' => 'ラズベリーとレザーの大胆な組み合わせ。', 'long_desc' => 'ラズベリーとレザーの大胆な組み合わせ「タスカンレザー」。上質のレザーを愛するトム フォードが生み出したこのセクシーなフレグランスは、レザーの動物的な香りとなめらかな質感を見事に表現しています。トップノート：ラズベリー、サフラン、タイム。ミドルノート：オリバナム（フランキンセンス）、ジャスミン。ベースノート：レザー、スエード、ウッディノート、アンバー。個性的でセクシーなフレグランス。', 'notes' => ['top' => 'ラズベリー、サフラン', 'middle' => 'レザー、ジャスミン', 'base' => 'アンバー、ウッディ'], 'variants' => [['sku' => 'TF-TL-50', 'size_ml' => 50, 'price_yen' => 39600, 'concentration' => 'EDP']]],
        ];
    }

    // === GUCCI (6 products) ===
    private function getGucciProducts(): array
    {
        return [
            ['brand_name' => 'グッチ', 'category_name' => 'フローラル EDP', 'name' => 'グッチ ブルーム オードパルファム', 'gender' => 'women', 'short_desc' => '自然の花々が咲き誇る庭園のような香り。', 'long_desc' => '自然の花々が咲き誇る庭園のような香り「グッチ ブルーム」。グッチ ブルーム オードパルファムは、多様で本物の女性たちの精神を体現する、豪華で豊かなホワイトフローラルフレグランス。トップノート：ネロリアコード、レモン、マンダリン、ベルガモット。ミドルノート：ジャスミンバッド、チューベローズ、ラングーンクリーパー。ベースノート：ムスク、サンダルウッド。アレッサンドロ・ミケーレが手がける、現代的なフローラルの香り。', 'notes' => ['top' => 'ジャスミン', 'middle' => 'チュベローズ', 'base' => 'ラングーンクリーパー'], 'featured' => true, 'variants' => [['sku' => 'GU-BLOOM-30', 'size_ml' => 30, 'price_yen' => 8250, 'concentration' => 'EDP'], ['sku' => 'GU-BLOOM-50', 'size_ml' => 50, 'price_yen' => 12100, 'concentration' => 'EDP'], ['sku' => 'GU-BLOOM-100', 'size_ml' => 100, 'price_yen' => 16500, 'concentration' => 'EDP']]],
            ['brand_name' => 'グッチ', 'category_name' => 'フローラル EDP', 'name' => 'グッチ ブルーム プロフーモディフィオーリ', 'gender' => 'women', 'short_desc' => 'より豊かで濃厚なブルーム。', 'long_desc' => 'オリジナルの「グッチ ブルーム オードパルファム」の華やかなホワイトフローラルの香りに、晴れやかなひねりを効かせたフレグランス。オリジナルの〔グッチ ブルーム〕の香りをベースに輝くようなアクセントを加えた Profumo di Fiori は、チュベローズを中心にジャスミンサンバック クローズドバッドとナチュラルガーデンニアの香りが調和。より豊かで濃厚なブルーム。', 'notes' => ['top' => 'ジャスミン、チュベローズ', 'middle' => 'イランイラン', 'base' => 'サンダルウッド、オリス'], 'variants' => [['sku' => 'GU-BLOOM-P-50', 'size_ml' => 50, 'price_yen' => 13500, 'concentration' => 'EDP']]],
            ['brand_name' => 'グッチ', 'category_name' => 'フローラル EDT', 'name' => 'グギルティ プールファム オードトワレ', 'gender' => 'women', 'short_desc' => '大胆でモダンな女性のための香り。', 'long_desc' => '大胆でモダンな女性のための香り「グッチ ギルティ プールファム」。あらゆる形の愛をたたえるシグネチャーフレグランス〔グッチ ギルティ プールファム〕。目立つこと、セクシーさをもたらす香り。それが GUILTY。トップノート：マンダリン、ピンクペッパー、コルシカンレモン。ミドルノート：ライラック、ゼラニウム、ピーチ。ベースノート：パチュリ、アンバー、ムスク。深みのあるアンバーとライラックが織り成す、フレッシュなフェミニンの競演。', 'notes' => ['top' => 'マンダリン、ピンクペッパー', 'middle' => 'ライラック、ゼラニウム', 'base' => 'パチュリ、アンバー'], 'variants' => [['sku' => 'GU-GUILTY-30', 'size_ml' => 30, 'price_yen' => 7700, 'concentration' => 'EDT'], ['sku' => 'GU-GUILTY-50', 'size_ml' => 50, 'price_yen' => 11000, 'concentration' => 'EDT']]],
            ['brand_name' => 'グッチ', 'category_name' => 'フローラル EDT', 'name' => 'グッチ フローラ ゴージャスガーデニア', 'gender' => 'women', 'short_desc' => 'ガーデニアを主役にしたフルーティフローラル。', 'long_desc' => 'ガーデニアを主役にしたフルーティフローラル「グッチ フローラ ゴージャスガーデニア」。2021 年発売。ガーデニアが開花した直後の軽快な香りと満開を迎えた時のうっとりするほど濃密な香りを表現したフレグランス。トップノート：ブロッサムアコード、イタリアンマンダリン、レッドベリー。ミドルノート：ホワイトガーデニア、ジャスミンアブソリュート、フランジパニ。ベースノート：ブラウンシュガー、パチュリ。華やかで女性らしい香り。', 'notes' => ['top' => 'レッドベリー、ペア', 'middle' => 'ガーデニア、フランジパニ', 'base' => 'パチュリ、ブラウンシュガー'], 'variants' => [['sku' => 'GU-FLORA-30', 'size_ml' => 30, 'price_yen' => 8250, 'concentration' => 'EDP'], ['sku' => 'GU-FLORA-50', 'size_ml' => 50, 'price_yen' => 12100, 'concentration' => 'EDP']]],
            ['brand_name' => 'グッチ', 'category_name' => 'フレッシュ EDT', 'name' => 'グッチ ギルティ プールオム オードトワレ', 'gender' => 'men', 'short_desc' => '現代的な男性のためのフレグランス。', 'long_desc' => 'グッチ ギルティにメンズラインが新発売。強烈で個性的でありながらも、現代的なフゼアが誘惑的に香ります。快楽主義的かつデカダンスな印象を持つこの香水は、ピリッとしたピンクペッパーと爽やかなイタリアンレモンのトップノートで幕を開けます。ミドルノートでは、伝統的に使用されてきたオレンジフラワーとフレンチラベンダーがブレンド。', 'notes' => ['top' => 'ラベンダー、レモン', 'middle' => 'オレンジフラワー', 'base' => 'シダー、パチュリ'], 'variants' => [['sku' => 'GU-GUILTY-M-50', 'size_ml' => 50, 'price_yen' => 9350, 'concentration' => 'EDT'], ['sku' => 'GU-GUILTY-M-90', 'size_ml' => 90, 'price_yen' => 13500, 'concentration' => 'EDT']]],
            ['brand_name' => 'グッチ', 'category_name' => 'ウッディ EDP', 'name' => 'グッチ インテンス ウード', 'gender' => 'unisex', 'short_desc' => 'ウードとスパイスの力強い香り。', 'long_desc' => '2016 年に発売されたユニセックス香水。香りは、スタンダードなオリエンタル・バルサムの香調がベース。ウード (香木) のスモーキーさをレザーで表現した、典型的なバルサム (樹脂) メインの香り。トム・フォード以下、高級香水ラインでトレンドを超えて記号化したタイプの香水。ピンクペッパーとベルガモットのトップから、セダーとガルバナムのミドルへ。', 'notes' => ['top' => 'ピンクペッパー、ベルガモット', 'middle' => 'セダー、ガルバナム', 'base' => 'ウード、アンバー'], 'variants' => [['sku' => 'GU-IOUD-50', 'size_ml' => 50, 'price_yen' => 14300, 'concentration' => 'EDP']]],
        ];
    }

    // === VERSACE (6 products) ===
    private function getVersaceProducts(): array
    {
        return [
            ['brand_name' => 'ヴェルサーチ', 'category_name' => 'フローラル EDT', 'name' => 'ブライトクリスタル オードトワレ', 'gender' => 'women', 'short_desc' => 'フレッシュでフルーティなフローラルの香り。', 'long_desc' => 'フレッシュでフルーティなフローラルの香り「ブライトクリスタル」。2006 年発売。マスターパフューマーのアルベルト・モリヤスによって調香された、フローラルフルーティフレグランス。トップノート：ザクロ、ユズ、アイスアコード。ミドルノート：ピオニー、マグノリア、ロータス。ベースノート：ムスク、マホガニー、アンバー。ヴェルサーチの女性を象徴する、自信に満ちた魅力的な香り。', 'notes' => ['top' => 'ユズ、ポメグラネート', 'middle' => 'ピオニー、マグノリア、ロータス', 'base' => 'ムスク、マホガニー、アンバー'], 'featured' => true, 'variants' => [['sku' => 'VS-BC-30', 'size_ml' => 30, 'price_yen' => 6270, 'concentration' => 'EDT'], ['sku' => 'VS-BC-50', 'size_ml' => 50, 'price_yen' => 8800, 'concentration' => 'EDT'], ['sku' => 'VS-BC-90', 'size_ml' => 90, 'price_yen' => 12100, 'concentration' => 'EDT']]],
            ['brand_name' => 'ヴェルサーチ', 'category_name' => 'フレッシュ EDT', 'name' => 'エロス オードトワレ', 'gender' => 'men', 'short_desc' => '力強く情熱的な男性のための香り。', 'long_desc' => '力強く情熱的な男性のための香り「エロス」。ギリシャ神話の愛の神エロスにインスパイアされた、パワフルで情熱的なフレグランス。トップノート：ミント、グリーンアップル、レモン。ミドルノート：トンカビーン、アンブロキサン、ゼラニウム。ベースノート：マダガスカルバニラ、ベチバー、オークモス、バージニアシダー。鮮烈なフレッシュさとウッディな温かみが調和した、男性的な魅力あふれる香り。', 'notes' => ['top' => 'ミント、レモン、グリーンアップル', 'middle' => 'トンカ、ジェノベーゼ', 'base' => 'バニラ、ベチバー、オークモス'], 'featured' => true, 'variants' => [['sku' => 'VS-EROS-50', 'size_ml' => 50, 'price_yen' => 7150, 'concentration' => 'EDT'], ['sku' => 'VS-EROS-100', 'size_ml' => 100, 'price_yen' => 9900, 'concentration' => 'EDT']]],
            ['brand_name' => 'ヴェルサーチ', 'category_name' => 'アロマティック EDT', 'name' => 'ディランブルー プールオム', 'gender' => 'men', 'short_desc' => '地中海の力強さと感性を表現した香り。', 'long_desc' => '地中海とそのカルチャーを思い起こさせるヴェルサーチのフレグランス。シトラスとベルガモットの爽やかなトップから、ヴァイオレットとペッパーのミドルノートへ。インセンスとサンダルウッドのウッディなベース。プレシャスな天然香料と最新の香料の組み合わせによるユニークなウッディの芳香は他のフレグランスとは一線を画する香り。', 'notes' => ['top' => 'シトラス、ベルガモット', 'middle' => 'ヴァイオレット、ペッパー', 'base' => 'インセンス、サンダルウッド'], 'variants' => [['sku' => 'VS-DB-50', 'size_ml' => 50, 'price_yen' => 7700, 'concentration' => 'EDT'], ['sku' => 'VS-DB-100', 'size_ml' => 100, 'price_yen' => 11000, 'concentration' => 'EDT']]],
            ['brand_name' => 'ヴェルサーチ', 'category_name' => 'フローラル EDT', 'name' => 'クリスタルノワール オードトワレ', 'gender' => 'women', 'short_desc' => '神秘的で官能的な香り。', 'long_desc' => 'ドナテッラ・ヴェルサーチが黒ダイヤをイメージしたボトルで、ラグジュアリーな存在感あふれるフレグランス。フローラルでオリエンタルなガーデニアの香りが古典的でミステリアスです。贅沢なイメージなので、華やかなパーティに出席する時におすすめです。ブラックカラントとビオラのトップから、ダリアとフランジパニのフローラルミドルへ。', 'notes' => ['top' => 'ブラックカラント、ビオラ', 'middle' => 'ダリア、フランジパニ', 'base' => 'バニラ、サンダルウッド、ムスク'], 'variants' => [['sku' => 'VS-CN-50', 'size_ml' => 50, 'price_yen' => 8800, 'concentration' => 'EDT']]],
            ['brand_name' => 'ヴェルサーチ', 'category_name' => 'フローラル EDT', 'name' => 'イエローダイヤモンド オードトワレ', 'gender' => 'women', 'short_desc' => '輝くような明るさとエレガンス。', 'long_desc' => 'ピュアな官能性、ピュアな透明感、ピュアな光、最高の美を持っている本物の宝石がフレッシュで鮮やかなフローラルの香りの中でヴェールを脱ぎました。真のフェミニティを表現したフレグランス。シトラスとペアのトップから、ミモザとフリージアのフローラルミドルへ。ムスクとパロサントのウッディなベース。', 'notes' => ['top' => 'シトラス、ペア', 'middle' => 'ミモザ、フリージア', 'base' => 'ムスク、パロサント'], 'variants' => [['sku' => 'VS-YD-50', 'size_ml' => 50, 'price_yen' => 7700, 'concentration' => 'EDT']]],
            ['brand_name' => 'ヴェルサーチ', 'category_name' => 'フレッシュ EDT', 'name' => 'マン オーフレッシュ', 'gender' => 'men', 'short_desc' => '軽やかでフレッシュな男性の香り。', 'long_desc' => '軽やかでフレッシュな男性の香り「マン オーフレッシュ」。2006 年発売。地中海の風と太陽を感じさせる、爽やかでエネルギッシュなフレグランス。トップノート：レモン、ベルガモット、ローズウッド。ミドルノート：ローズ、カルダモン、シダー。ベースノート：ムスク、アンバー、ウッディノート。アクアティックでフルーティな香り。', 'notes' => ['top' => 'レモン、ベルガモット', 'middle' => 'ローズ、カルダモン', 'base' => 'ムスク、シダー'], 'variants' => [['sku' => 'VS-MOF-50', 'size_ml' => 50, 'price_yen' => 7150, 'concentration' => 'EDT']]],
        ];
    }

    // === CHLOE (6 products) ===
    private function getChloeProducts(): array
    {
        return [
            ['brand_name' => 'クロエ', 'category_name' => 'フローラル EDP', 'name' => 'クロエ オードパルファム', 'gender' => 'women', 'short_desc' => '上品でフェミニンなローズの香り。', 'long_desc' => '上品でフェミニンなローズの香り「クロエ」。2008 年発売。すぐにフレッシュでロマンティック、自信に満ちて個性的な、リッチで複雑なオードパルファム。トップノート：ピオニー、ライチ、フリージア。ミドルノート：ローズ、リリーオブザバレー、マグノリア。ベースノート：シダー、アンバーグリス、ハニー。クロエの精神をカプセル化した、女性的でフローラルなフレグランス。', 'notes' => ['top' => 'ピオニー、フリージア', 'middle' => 'ローズ、リリーオブザバレー', 'base' => 'シダー、ムスク、アンバー'], 'featured' => true, 'variants' => [['sku' => 'CHLOE-EDP-30', 'size_ml' => 30, 'price_yen' => 8250, 'concentration' => 'EDP'], ['sku' => 'CHLOE-EDP-50', 'size_ml' => 50, 'price_yen' => 12100, 'concentration' => 'EDP'], ['sku' => 'CHLOE-EDP-75', 'size_ml' => 75, 'price_yen' => 15400, 'concentration' => 'EDP']]],
            ['brand_name' => 'クロエ', 'category_name' => 'ウッディ EDP', 'name' => 'ノマド オードパルファム', 'gender' => 'women', 'short_desc' => 'ミラベルプラムとオークモスの組み合わせ。', 'long_desc' => 'ミラベルプラムとオークモスの組み合わせ「ノマド」。2018 年発売。自由な精神と冒険心を表現した、シプレーフローラルフレグランス。トップノート：ミラベルプラム、レモン。ミドルノート：フリージア、ローズ、ジャスミン。ベースノート：オークモス、サンダルウッド、アンバー。新鮮でフローラル、そしてアーシーな香りで、複雑なブレンドが特徴。', 'notes' => ['top' => 'ミラベルプラム', 'middle' => 'フリージア', 'base' => 'オークモス、サンダルウッド'], 'featured' => true, 'variants' => [['sku' => 'CHLOE-NOM-30', 'size_ml' => 30, 'price_yen' => 8250, 'concentration' => 'EDP'], ['sku' => 'CHLOE-NOM-50', 'size_ml' => 50, 'price_yen' => 12100, 'concentration' => 'EDP']]],
            ['brand_name' => 'クロエ', 'category_name' => 'フローラル EDP', 'name' => 'ローズタンジェリン オードトワレ', 'gender' => 'women', 'short_desc' => 'タンジェリンとローズの組み合わせ。', 'long_desc' => 'タンジェリンとローズの組み合わせ「ローズタンジェリン」。2019 年発売。フレッシュでシトラスなローズの香り。トップノート：タンジェリン、シトラス。ミドルノート：ローズ、ピーオニー。ベースノート：シダー、ムスク。明るく爽やかな、日常使いに最適なフレグランス。', 'notes' => ['top' => 'タンジェリン、シトラス', 'middle' => 'ローズ', 'base' => 'シダー、ムスク'], 'variants' => [['sku' => 'CHLOE-RT-30', 'size_ml' => 30, 'price_yen' => 7150, 'concentration' => 'EDT']]],
            ['brand_name' => 'クロエ', 'category_name' => 'フローラル EDT', 'name' => 'クロエ ローズ オードトワレ', 'gender' => 'women', 'short_desc' => '軽やかなローズの香り。', 'long_desc' => '軽やかなローズの香り「クロエ ローズ」。2015 年発売。クロエのアイコニックなローズの香りを、より軽やかに表現したオードトワレ。トップノート：ローズ、シトラス。ミドルノート：フローラル。ベースノート：ムスク、シダー。ピュアでフェミニンな、日常にぴったりの香り。', 'notes' => ['top' => 'ローズ、シトラス', 'middle' => 'フローラル', 'base' => 'ムスク、シダー'], 'variants' => [['sku' => 'CHLOE-ROSE-50', 'size_ml' => 50, 'price_yen' => 9900, 'concentration' => 'EDT']]],
            ['brand_name' => 'クロエ', 'category_name' => 'フローラル EDP', 'name' => 'クロエ ナチュレル', 'gender' => 'women', 'short_desc' => 'ナチュラルでオーガニックな印象の香り。', 'long_desc' => 'ナチュラルでオーガニックな印象の香り「クロエ ナチュレル」。2017 年発売。99% 天然由来成分を使用した、エコフレンドリーなフレグランス。トップノート：シトラス、フローラル。ミドルノート：ローズ、ジャスミン。ベースノート：シダー、ムスク。ナチュラルでピュアな、現代的な女性の香り。', 'notes' => ['top' => 'シトラス、フローラル', 'middle' => 'ローズ、ジャスミン', 'base' => 'シダー、ムスク'], 'variants' => [['sku' => 'CHLOE-NAT-50', 'size_ml' => 50, 'price_yen' => 12100, 'concentration' => 'EDP']]],
            ['brand_name' => 'クロエ', 'category_name' => 'フローラル EDP', 'name' => 'クロエ ルミヌーズ', 'gender' => 'women', 'short_desc' => '光を放つような明るいフローラル。', 'long_desc' => '光を放つような明るいフローラル「クロエ ルミヌーズ」。2019 年発売。光り輝くような、明るくフェミニンなフローラルフレグランス。トップノート：フローラル、シトラス。ミドルノート：ローズ、ピオニー。ベースノート：ムスク、アンバー。女性らしさと輝きを表現した、エレガントな香り。', 'notes' => ['top' => 'フローラル、シトラス', 'middle' => 'ローズ、ピオニー', 'base' => 'ムスク、アンバー'], 'variants' => [['sku' => 'CHLOE-LUM-50', 'size_ml' => 50, 'price_yen' => 12100, 'concentration' => 'EDP']]],
        ];
    }

    // === YSL (6 products) ===
    private function getYslProducts(): array
    {
        return [
            ['brand_name' => 'イヴ・サンローラン', 'category_name' => 'オリエンタル EDP', 'name' => 'ブラックオピウム オードパルファム', 'gender' => 'women', 'short_desc' => 'コーヒーとバニラの中毒的な香り。', 'long_desc' => 'コーヒーとバニラの中毒的な香り「ブラックオピウム」。2014 年発売。イヴ・サンローランのアイコニックなフレグランス。甘く強烈なフレグランス。ブラックコーヒーのコードとセンシュアルなバニラを注入し、オレンジブロッサム、ホワイトフラワー、パチュリ、ホワイトムスクで優しくバランスを取った、甘く強烈なフレグランス。トップノート：コーヒー、ピンクペッパー。ミドルノート：オレンジブロッサム、ジャスミン。ベースノート：バニラ、パチュリ、シダー。', 'notes' => ['top' => 'コーヒー、ピンクペッパー', 'middle' => 'オレンジブロッサム、ジャスミン', 'base' => 'バニラ、パチュリ、シダー'], 'featured' => true, 'variants' => [['sku' => 'YSL-BO-30', 'size_ml' => 30, 'price_yen' => 8250, 'concentration' => 'EDP'], ['sku' => 'YSL-BO-50', 'size_ml' => 50, 'price_yen' => 12100, 'concentration' => 'EDP'], ['sku' => 'YSL-BO-90', 'size_ml' => 90, 'price_yen' => 16500, 'concentration' => 'EDP']]],
            ['brand_name' => 'イヴ・サンローラン', 'category_name' => 'フローラル EDP', 'name' => 'リブレ オードパルファム', 'gender' => 'women', 'short_desc' => 'ラベンダーとオレンジブロッサムのコントラスト。', 'long_desc' => 'ラベンダーとオレンジブロッサムのコントラスト「リブル」。2019 年発売。自由を象徴する、大胆で官能的なフレグランス。トップノート：ラベンダー、マンダリン、ブラックカラント、プチグレン。ミドルノート：オレンジブロッサム、ジャスミン。ベースノート：マダガスカルバニラ、ムスク、シダー。ラベンダーとベルガモットがトップノートでフレッシュな香りを放ち、オレンジブロッサムとジャスミンがハートノートでセクシーな香りを放ちます。', 'notes' => ['top' => 'ラベンダー、マンダリン', 'middle' => 'オレンジブロッサム、ジャスミン', 'base' => 'バニラ、ムスク、シダー'], 'variants' => [['sku' => 'YSL-LIB-30', 'size_ml' => 30, 'price_yen' => 8250, 'concentration' => 'EDP'], ['sku' => 'YSL-LIB-50', 'size_ml' => 50, 'price_yen' => 12100, 'concentration' => 'EDP'], ['sku' => 'YSL-LIB-90', 'size_ml' => 90, 'price_yen' => 16500, 'concentration' => 'EDP']]],
            ['brand_name' => 'イヴ・サンローラン', 'category_name' => 'ウッディ EDT', 'name' => 'Y オードパルファム', 'gender' => 'men', 'short_desc' => 'リンゴとセージのフレッシュな香り。', 'long_desc' => 'リンゴとセージのフレッシュな香り「Y オードパルファム」。2017 年発売。現代的な男性のための、フレッシュでアロマティックなフレグランス。トップノート：アップル、ジンジャー、ベルガモット。ミドルノート：セージ、ジュニパー。ベースノート：アンバーウッド、トンカビーン。爽やかで洗練された、日常使いに最適な香り。', 'notes' => ['top' => 'アップル、ジンジャー、ベルガモット', 'middle' => 'セージ、ジュニパー', 'base' => 'アンバーウッド、トンカ'], 'variants' => [['sku' => 'YSL-Y-60', 'size_ml' => 60, 'price_yen' => 9900, 'concentration' => 'EDP'], ['sku' => 'YSL-Y-100', 'size_ml' => 100, 'price_yen' => 14300, 'concentration' => 'EDP']]],
            ['brand_name' => 'イヴ・サンローラン', 'category_name' => 'フローラル EDP', 'name' => 'モンパリ オードパルファム', 'gender' => 'women', 'short_desc' => 'パリの街をイメージした甘くロマンティックな香り。', 'long_desc' => 'パリの街をイメージした甘くロマンティックな香り「モンパリ」。2016 年発売。愛の街パリにインスパイアされた、フローラルフルーティフレグランス。トップノート：ストロベリー、ラズベリー、ペア、オレンジ、タンジェリン、カラブリアンベルガモット。ミドルノート：ダチュラ、ジャスミン、ホワイトピーオニー。ベースノート：パチュリ、バニラ、ホワイトシプレ。甘く魅惑的な、ロマンティックな香り。', 'notes' => ['top' => 'ストロベリー、ラズベリー、ペア', 'middle' => 'ダチュラ、ジャスミン', 'base' => 'パチュリ、バニラ'], 'variants' => [['sku' => 'YSL-MP-30', 'size_ml' => 30, 'price_yen' => 8250, 'concentration' => 'EDP'], ['sku' => 'YSL-MP-50', 'size_ml' => 50, 'price_yen' => 12100, 'concentration' => 'EDP']]],
            ['brand_name' => 'イヴ・サンローラン', 'category_name' => 'アロマティック EDT', 'name' => 'ラニュイドゥロム オードトワレ', 'gender' => 'men', 'short_desc' => 'カルダモンとシダーの魅惑的な香り。', 'long_desc' => 'カルダモンとシダーの魅惑的な香り「ラニュイドゥロム」。2016 年発売。洗練された男性のための、アロマティックウッディフレグランス。トップノート：ジンジャー、グレープフルーツ、カルダモン、ベルガモット。ミドルノート：ローズ、セージ、ゼラニウム、アップル。ベースノート：シダー、ベチバー、キャッシュメアウッド。スパイシーでフレッシュな香りが、男性的な魅力を引き立てます。', 'notes' => ['top' => 'カルダモン、ベルガモット', 'middle' => 'ラベンダー、ベチバー', 'base' => 'バニラ、シダー'], 'variants' => [['sku' => 'YSL-LN-60', 'size_ml' => 60, 'price_yen' => 8800, 'concentration' => 'EDT'], ['sku' => 'YSL-LN-100', 'size_ml' => 100, 'price_yen' => 12650, 'concentration' => 'EDT']]],
            ['brand_name' => 'イヴ・サンローラン', 'category_name' => 'オリエンタル EDP', 'name' => 'オピウム オードパルファム', 'gender' => 'women', 'short_desc' => '伝説的なクラシックフレグランス。', 'long_desc' => '伝説的なクラシックフレグランス「オピウム」。1977 年発売。イヴ・サンローランの伝説的なフレグランス。オリエンタルスパイシーの香調がベース。トップノート：コリアンダー、プラム、マンダリン。ミドルノート：ジャスミン、ローズ、オリス。ベースノート：アンバー、パチュリ、ムスク。官能的でミステリアスな、時代を超えた名香。', 'notes' => ['top' => 'コリアンダー、プラム', 'middle' => 'ジャスミン、ローズ', 'base' => 'アンバー、パチュリ'], 'variants' => [['sku' => 'YSL-OPI-30', 'size_ml' => 30, 'price_yen' => 9350, 'concentration' => 'EDP']]],
        ];
    }

    // === PRADA (6 products) ===
    private function getPradaProducts(): array
    {
        return [
            ['brand_name' => 'プラダ', 'category_name' => 'フローラル EDP', 'name' => 'プラダ パラドックス オードパルファム', 'gender' => 'women', 'short_desc' => '矛盾を楽しむ現代の女性のための香り。', 'long_desc' => '矛盾を楽しむ現代の女性のための香り「パラドックス」。2022 年発売。フローラルアンバーのフレグランス。トップノート：ペア、タンジェリン、ベルガモット。ミドルノート：オレンジブロッサム、ネロリエッセンス、ジャスミンサンバック。ベースノート：バニラ、ベチバー、ホワイトムスク。エネルギーに満ちた第一印象から、エレガントなフローラルへ、そして温かみのあるベースへと移り変わる、現代的な女性の香りを表現。', 'notes' => ['top' => 'ペア、タンジェリン', 'middle' => 'オレンジフラワー、ジャスミン', 'base' => 'バニラ、ベチバー、ホワイトムスク'], 'featured' => true, 'variants' => [['sku' => 'PR-PAR-30', 'size_ml' => 30, 'price_yen' => 9900, 'concentration' => 'EDP'], ['sku' => 'PR-PAR-50', 'size_ml' => 50, 'price_yen' => 14300, 'concentration' => 'EDP'], ['sku' => 'PR-PAR-90', 'size_ml' => 90, 'price_yen' => 19800, 'concentration' => 'EDP']]],
            ['brand_name' => 'プラダ', 'category_name' => 'アロマティック EDT', 'name' => 'ルナロッサ オードトワレ', 'gender' => 'men', 'short_desc' => 'ラベンダーとオレンジのフレッシュな組み合わせ。', 'long_desc' => 'ラベンダーとオレンジのフレッシュな組み合わせ「ルナロッサ」。トップノート：ラベンダー、オレンジ。ミドルノート：ミント、クレモナ。ベースノート：アンバー、バニラ。爽やかで洗練された、日常使いに最適なフレグランス。', 'notes' => ['top' => 'ラベンダー、オレンジ', 'middle' => 'ミント、クレモナ', 'base' => 'アンバー、バニラ'], 'variants' => [['sku' => 'PR-LR-50', 'size_ml' => 50, 'price_yen' => 9350, 'concentration' => 'EDT'], ['sku' => 'PR-LR-100', 'size_ml' => 100, 'price_yen' => 13200, 'concentration' => 'EDT']]],
            ['brand_name' => 'プラダ', 'category_name' => 'アロマティック EDT', 'name' => 'ルナロッサ オーシャン オードトワレ', 'gender' => 'men', 'short_desc' => '海のエネルギーを感じさせるアクアティックフレグランス。', 'long_desc' => '海のエネルギーを感じさせるアクアティックフレグランス「ルナロッサ オーシャン」。トップノート：アクアティックノート、ベルガモット。ミドルノート：アイリス、ラベンダー。ベースノート：パチュリ、オークモス。清涼感あふれる、アクアティックな香り。', 'notes' => ['top' => 'アクアティックノート、ベルガモット', 'middle' => 'アイリス、ラベンダー', 'base' => 'パチュリ、オークモス'], 'variants' => [['sku' => 'PR-LRO-50', 'size_ml' => 50, 'price_yen' => 9900, 'concentration' => 'EDT']]],
            ['brand_name' => 'プラダ', 'category_name' => 'フローラル EDP', 'name' => 'キャンディ オードパルファム', 'gender' => 'women', 'short_desc' => 'キャラメルの甘く愛らしい香り。', 'long_desc' => 'キャラメルの甘く愛らしい香り「キャンディ」。トップノート：シトラス。ミドルノート：ピオニー。ベースノート：キャラメル、バニラ、ベンゾイン。甘く官能的な、女性らしいフレグランス。', 'notes' => ['top' => 'シトラス', 'middle' => 'ピオニー', 'base' => 'キャラメル、バニラ、ベンゾイン'], 'variants' => [['sku' => 'PR-CAN-30', 'size_ml' => 30, 'price_yen' => 8250, 'concentration' => 'EDP'], ['sku' => 'PR-CAN-50', 'size_ml' => 50, 'price_yen' => 12100, 'concentration' => 'EDP']]],
            ['brand_name' => 'プラダ', 'category_name' => 'フローラル EDP', 'name' => 'プラダ パラドックス インテンス', 'gender' => 'women', 'short_desc' => 'より深みのあるパラドックス。', 'long_desc' => 'より深みのあるパラドックス「パラドックス インテンス」。トップノート：ペア。ミドルノート：ジャスミン、ローズ。ベースノート：バニラ、アンバー。オリジナルのパラドックスよりも濃厚で、深みのある香り。', 'notes' => ['top' => 'ペア', 'middle' => 'ジャスミン、ローズ', 'base' => 'バニラ、アンバー'], 'variants' => [['sku' => 'PR-PARI-50', 'size_ml' => 50, 'price_yen' => 15400, 'concentration' => 'EDP']]],
            ['brand_name' => 'プラダ', 'category_name' => 'ウッディ EDP', 'name' => 'ローミュ オードパルファム', 'gender' => 'men', 'short_desc' => '高級皮革のような洗練された香り。', 'long_desc' => '高級皮革のような洗練された香り「ローミュ」。トップノート：ベルガモット、ピンクペッパー。ミドルノート：ラベンダー、ゼラニウム。ベースノート：レザー、アンバー。洗練された男性のための、ウッディフレグランス。', 'notes' => ['top' => 'ベルガモット、ピンクペッパー', 'middle' => 'ラベンダー、ゼラニウム', 'base' => 'レザー、アンバー'], 'variants' => [['sku' => 'PR-LHOM-50', 'size_ml' => 50, 'price_yen' => 11000, 'concentration' => 'EDP']]],
        ];
    }

    // === ARMANI (6 products) ===
    private function getArmaniProducts(): array
    {
        return [
            ['brand_name' => 'ジョルジオ・アルマーニ', 'category_name' => 'アロマティック EDT', 'name' => 'アクアディジオ オードトワレ', 'gender' => 'men', 'short_desc' => '海と太陽を感じさせるクラシックなフレグランス。', 'long_desc' => '海と太陽を感じさせるクラシックなフレグランス「アクアディジオ」。1996 年発売。アクアティック、ヒヤシンスのフレグランス。トップノート：カラブリアンベルガモット、ネロリ、グリーンタンジェリン。ミドルノート：ジャスミン、スズラン、ローズマリー。ベースノート：パチュリ、ホワイトムスク、シダー。地中海の爽やかさと、太陽の温もりを表現した、不朽の名香。', 'notes' => ['top' => 'ライム、レモン、ベルガモット', 'middle' => 'ジャスミン、スズラン、ローズマリー', 'base' => 'パチュリ、ホワイトムスク、シダー'], 'featured' => true, 'variants' => [['sku' => 'GA-ADG-50', 'size_ml' => 50, 'price_yen' => 9350, 'concentration' => 'EDT'], ['sku' => 'GA-ADG-100', 'size_ml' => 100, 'price_yen' => 13200, 'concentration' => 'EDT'], ['sku' => 'GA-ADG-200', 'size_ml' => 200, 'price_yen' => 18700, 'concentration' => 'EDT']]],
            ['brand_name' => 'ジョルジオ・アルマーニ', 'category_name' => 'ウッディ EDP', 'name' => 'アクアディジオ オードパルファム', 'gender' => 'men', 'short_desc' => 'より深みのあるアクアディジオ。', 'long_desc' => 'より深みのあるアクアディジオ「アクアディジオ オードパルファム」。トップノート：マリンノート、ベルガモット。ミドルノート：ローズマリー、セージ。ベースノート：インセンス、パチュリ。オリジナルのアクアディジオよりも濃厚で、深みのある香り。', 'notes' => ['top' => 'マリンノート、ベルガモット', 'middle' => 'ローズマリー、セージ', 'base' => 'インセンス、パチュリ'], 'variants' => [['sku' => 'GA-ADG-EDP-50', 'size_ml' => 50, 'price_yen' => 11000, 'concentration' => 'EDP'], ['sku' => 'GA-ADG-EDP-100', 'size_ml' => 100, 'price_yen' => 15400, 'concentration' => 'EDP']]],
            ['brand_name' => 'ジョルジオ・アルマーニ', 'category_name' => 'フローラル EDP', 'name' => 'シー オードパルファム', 'gender' => 'women', 'short_desc' => 'ブラックカラントとバニラの組み合わせ。', 'long_desc' => 'ブラックカラントとバニラの組み合わせ「シー」。2013 年発売。トップノート：ブラックカラント、シトラス。ミドルノート：ローズ、ジャスミン、フリージア。ベースノート：バニラ、パチュリ、ウッディ、オルカノックス。エレガントで洗練された、現代的な女性のフレグランス。', 'notes' => ['top' => 'ブラックカラント、シトラス', 'middle' => 'ローズ、ジャスミン', 'base' => 'バニラ、パチュリ、ウッディ'], 'variants' => [['sku' => 'GA-SI-30', 'size_ml' => 30, 'price_yen' => 8800, 'concentration' => 'EDP'], ['sku' => 'GA-SI-50', 'size_ml' => 50, 'price_yen' => 13200, 'concentration' => 'EDP'], ['sku' => 'GA-SI-100', 'size_ml' => 100, 'price_yen' => 18700, 'concentration' => 'EDP']]],
            ['brand_name' => 'ジョルジオ・アルマーニ', 'category_name' => 'オリエンタル EDP', 'name' => 'コード プールファム', 'gender' => 'women', 'short_desc' => 'オレンジブロッサムとバニラの魅惑的な香り。', 'long_desc' => 'オレンジブロッサムとバニラの魅惑的な香り「コード プールファム」。トップノート：イタリアンオレンジ、ジャスミン、ビターオレンジ。ミドルノート：オレンジブロッサム、ジャスミン、ジンジャー。ベースノート：ハニー、バニラ、サンダルウッド。官能的で魅惑的な、オリエンタルフローラルフレグランス。', 'notes' => ['top' => 'イタリアンマンダリン、オレンジ', 'middle' => 'オレンジブロッサム、ジャスミン', 'base' => 'バニラ、ハニー'], 'variants' => [['sku' => 'GA-CODE-30', 'size_ml' => 30, 'price_yen' => 9350, 'concentration' => 'EDP'], ['sku' => 'GA-CODE-50', 'size_ml' => 50, 'price_yen' => 13750, 'concentration' => 'EDP']]],
            ['brand_name' => 'ジョルジオ・アルマーニ', 'category_name' => 'フレッシュ EDT', 'name' => 'コード プールオム オードトワレ', 'gender' => 'men', 'short_desc' => 'レモンとオリーブのフレッシュな香り。', 'long_desc' => 'レモンとオリーブのフレッシュな香り「コード プールオム」。トップノート：レモン、ベルガモット。ミドルノート：オリーブフラワー、スターアニス。ベースノート：レザー、ギアウッド、タバコ。洗練された男性のための、アロマティックフレグランス。', 'notes' => ['top' => 'レモン、ベルガモット', 'middle' => 'オリーブフラワー、スターアニス', 'base' => 'レザー、ギアウッド、タバコ'], 'variants' => [['sku' => 'GA-CODEM-50', 'size_ml' => 50, 'price_yen' => 9350, 'concentration' => 'EDT'], ['sku' => 'GA-CODEM-100', 'size_ml' => 100, 'price_yen' => 13200, 'concentration' => 'EDT']]],
            ['brand_name' => 'ジョルジオ・アルマーニ', 'category_name' => 'ウッディ EDT', 'name' => 'ストロンガーウィズユー オードトワレ', 'gender' => 'men', 'short_desc' => 'バニラと栗の温かみのある香り。', 'long_desc' => 'バニラと栗の温かみのある香り「ストロンガーウィズユー」。トップノート：バイオレット、チェストナッツ。ミドルノート：セージ。ベースノート：バニラ、ムスク。温かみのある、スパイシーフレグランス。', 'notes' => ['top' => 'バイオレット、チェストナッツ', 'middle' => 'セージ', 'base' => 'バニラ、ムスク'], 'variants' => [['sku' => 'GA-SWU-50', 'size_ml' => 50, 'price_yen' => 9350, 'concentration' => 'EDT']]],
        ];
    }

    // === JO MALONE (6 products) ===
    private function getJoMaloneProducts(): array
    {
        return [
            ['brand_name' => 'ジョーマローン', 'category_name' => 'シトラス EDT', 'name' => 'ライムバジル＆マンダリン コロン', 'gender' => 'unisex', 'short_desc' => 'カリブ海の風を感じさせる爽やかなシトラス。', 'long_desc' => 'カリブ海の風を感じさせる爽やかなシトラス「ライムバジル＆マンダリン」。1999 年発売。ジョーマローンのシグネチャーフレグランス。トップノート：ライム、ベルガモット、マンダリン。ミドルノート：バジル、タイム、アイリス、ライラック。ベースノート：ベチバー、パチュリ。ペッパーリーなバジルとアロマティックなホワイトタイムが、ライムの香りに予想外のひねりを加えた、モダンクラシック。', 'notes' => ['top' => 'ライム、マンダリン', 'middle' => 'バジル、タイム', 'base' => 'リリー、ベチバー'], 'featured' => true, 'variants' => [['sku' => 'JM-LBM-30', 'size_ml' => 30, 'price_yen' => 8800, 'concentration' => 'EDC'], ['sku' => 'JM-LBM-100', 'size_ml' => 100, 'price_yen' => 17600, 'concentration' => 'EDC']]],
            ['brand_name' => 'ジョーマローン', 'category_name' => 'フルーティー EDT', 'name' => 'イングリッシュペアー＆フリージア コロン', 'gender' => 'unisex', 'short_desc' => '熟したペアーと白いフリージアの組み合わせ。', 'long_desc' => '熟したペアーと白いフリージアの組み合わせ「イングリッシュペアー＆フリージア」。2010 年発売。トップノート：キングウィリアムペアー、メロン。ミドルノート：フリージア、ローズ。ベースノート：パチュリ、アンバー、プレシャスウッド。果樹園が豊かに実る秋の風景を表現した、フルーティフローラルフレグランス。', 'notes' => ['top' => 'キングウィリアムペアー', 'middle' => 'フリージア', 'base' => 'パチュリ'], 'featured' => true, 'variants' => [['sku' => 'JM-EPF-30', 'size_ml' => 30, 'price_yen' => 8800, 'concentration' => 'EDC'], ['sku' => 'JM-EPF-100', 'size_ml' => 100, 'price_yen' => 17600, 'concentration' => 'EDC']]],
            ['brand_name' => 'ジョーマローン', 'category_name' => 'ウッディ EDT', 'name' => 'ウッドセージ＆シーソルト コロン', 'gender' => 'unisex', 'short_desc' => '海風とミネラルを感じさせるフレッシュなウッディ。', 'long_desc' => '海風とミネラルを感じさせるフレッシュなウッディ「ウッドセージ＆シーソルト」。2014 年発売。トップノート：シーソルト。ミドルノート：セージ。ベースノート：グレープフルーツ、ムスク。海岸の崖を吹き抜ける風を表現した、爽やかで自然な香り。', 'notes' => ['top' => 'シーソルト', 'middle' => 'セージ', 'base' => 'グラープフルーツ、ムスク'], 'variants' => [['sku' => 'JM-WSS-30', 'size_ml' => 30, 'price_yen' => 8800, 'concentration' => 'EDC'], ['sku' => 'JM-WSS-100', 'size_ml' => 100, 'price_yen' => 17600, 'concentration' => 'EDC']]],
            ['brand_name' => 'ジョーマローン', 'category_name' => 'フローラル EDT', 'name' => 'ワイルドブルーベル コロン', 'gender' => 'women', 'short_desc' => 'ブルーベルの花が咲き誇る森の香り。', 'long_desc' => 'ブルーベルの花が咲き誇る森の香り「ワイルドブルーベル」。2011 年発売。トップノート：ブルーベル。ミドルノート：クローブ、リリー。ベースノート：ムスク。朝露に濡れたブルーベルの森を表現した、フレッシュでフローラルな香り。', 'notes' => ['top' => 'ブルーベル', 'middle' => 'クローブ、リリー', 'base' => 'ムスク'], 'variants' => [['sku' => 'JM-WB-30', 'size_ml' => 30, 'price_yen' => 8800, 'concentration' => 'EDC'], ['sku' => 'JM-WB-100', 'size_ml' => 100, 'price_yen' => 17600, 'concentration' => 'EDC']]],
            ['brand_name' => 'ジョーマローン', 'category_name' => 'フローラル EDT', 'name' => 'ピオニー＆ブラッシュスエード コロン', 'gender' => 'women', 'short_desc' => '華やかなピオニーとスエードの組み合わせ。', 'long_desc' => '華やかなピオニーとスエードの組み合わせ「ピオニー＆ブラッシュスエード」。2013 年発売。トップノート：レッドアップル。ミドルノート：ピオニー。ベースノート：スエード。ロマンティックでフェミニンな、フローラルフレグランス。', 'notes' => ['top' => 'レッドアップル', 'middle' => 'ピオニー', 'base' => 'スエード'], 'variants' => [['sku' => 'JM-PBS-30', 'size_ml' => 30, 'price_yen' => 8800, 'concentration' => 'EDC'], ['sku' => 'JM-PBS-100', 'size_ml' => 100, 'price_yen' => 17600, 'concentration' => 'EDC']]],
            ['brand_name' => 'ジョーマローン', 'category_name' => 'フルーティー EDT', 'name' => 'ネクタリンブロッサム＆ハニー コロン', 'gender' => 'women', 'short_desc' => 'ネクタリンの甘さと蜂蜜の温かみ。', 'long_desc' => 'ネクタリンの甘さと蜂蜜の温かみ「ネクタリンブロッサム＆ハニー」。2004 年発売。トップノート：ネクタリン。ミドルノート：アカシアハニー。ベースノート：ピーチ、プラム。甘くフルーティな、爽やかなフレグランス。', 'notes' => ['top' => 'ネクタリン', 'middle' => 'アカシアハニー', 'base' => 'ピーチ'], 'variants' => [['sku' => 'JM-NBH-30', 'size_ml' => 30, 'price_yen' => 8800, 'concentration' => 'EDC']]],
        ];
    }
}
